
CREATE TABLE T_TENANT
(
	TEN_TECHID BIGINT IDENTITY(1,1) NOT NULL,
	TEN_READABLE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TEN_ID PRIMARY KEY CLUSTERED (TEN_TECHID)
)

/*------------------------------------------- ASSET -------------------------------------------*/
CREATE TABLE T_ASS_SPACE
(
	SPA_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	SPA_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	SPA_ENDTIME datetime2(7) DEFAULT NULL,
	SPA_READABLE VARCHAR(50) DEFAULT NULL,
	SPA_FK_TEN_TENANT BIGINT NULL ,

	CONSTRAINT PK_SPA_TECHID PRIMARY KEY CLUSTERED (SPA_TECHID),
	CONSTRAINT FK_SPA_FK_TEN_TENANT FOREIGN KEY (SPA_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID)
)

CREATE TABLE T_ASS_ASSET_TYPE
(
	AST_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	AST_READABLE VARCHAR(50) DEFAULT NULL,
	AST_BEGTIME datetime2(7)  DEFAULT SYSDATETIME ( ),
	AST_ENDTIME datetime2(7) DEFAULT NULL,
	AST_FK_TEN_TENANT BIGINT NULL ,

	AST_REFID VARCHAR(50) NOT NULL,
	AST_CONCRETE BIT DEFAULT 1,
	AST_LOCALIZABLE VARCHAR(10) DEFAULT 'No',
	AST_FK_SPA_SPACE BIGINT NOT NULL,
	AST_FK_AST_SUPER_TYPE BIGINT DEFAULT NULL,

	CONSTRAINT PK_AST_TECHID PRIMARY KEY CLUSTERED (AST_TECHID),
	CONSTRAINT FK_AST_FK_TEN_TENANT FOREIGN KEY (AST_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_AST_FK_AST_SUPER_TYPE FOREIGN KEY (AST_FK_AST_SUPER_TYPE) REFERENCES T_ASS_ASSET_TYPE (AST_TECHID),
	CONSTRAINT FK_AST_FK_SPA_SPACE FOREIGN KEY (AST_FK_SPA_SPACE) REFERENCES T_ASS_SPACE (SPA_TECHID)
)
CREATE INDEX I_AST_TECHID ON T_ASS_ASSET_TYPE (AST_TECHID ASC)
CREATE INDEX I_AST_REFID ON T_ASS_ASSET_TYPE (AST_REFID ASC)


CREATE TABLE T_ASS_ASSET_TYPE_PART
(
	ATP_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	ATP_FK_TEN_TENANT BIGINT NULL ,
	ATP_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	ATP_ENDTIME datetime2(7) DEFAULT NULL,

	ATP_FK_AST_PART BIGINT NOT NULL,
	ATP_FK_AST_PARTOF BIGINT NOT NULL,
	ATP_CARD_MIN INTEGER DEFAULT 0,
	ATP_CARD_MAX INTEGER NULL,

	CONSTRAINT OK_ATP_TECHID PRIMARY KEY CLUSTERED (ATP_TECHID),
	CONSTRAINT FK_ATP_FK_TEN_TENANT FOREIGN KEY (ATP_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_ATP_FK_AST_PART FOREIGN KEY (ATP_FK_AST_PART) REFERENCES T_ASS_ASSET_TYPE (AST_TECHID),
	CONSTRAINT FK_ATP_FK_AST_PARTOF FOREIGN KEY (ATP_FK_AST_PARTOF) REFERENCES T_ASS_ASSET_TYPE(AST_TECHID)
)
CREATE INDEX I_ATP_TECHID ON T_ASS_ASSET_TYPE_PART (ATP_TECHID ASC)
CREATE INDEX I_ATP_FK_AST_PART ON T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART ASC)
CREATE INDEX I_ATP_FK_AST_PARTOF ON T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PARTOF ASC)

CREATE TABLE T_ASS_PROPERTY_TYPE
(
	APT_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	APT_READABLE VARCHAR(50) DEFAULT NULL,
	APT_FK_TEN_TENANT BIGINT NULL ,

	APT_FK_AST_TYPE BIGINT NOT NULL,
	APT_FORMAT VARCHAR(32) NOT NULL,
    CONSTRAINT PK_APT_TECHID PRIMARY KEY CLUSTERED (APT_TECHID),
	CONSTRAINT FK_APT_FK_TEN_TENANT FOREIGN KEY (APT_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_APT_FK_AST_TYPE FOREIGN KEY (APT_FK_AST_TYPE) REFERENCES T_ASS_ASSET_TYPE(AST_TECHID)
)
CREATE INDEX I_APT_TECHID ON T_ASS_PROPERTY_TYPE (APT_TECHID ASC)
CREATE INDEX I_APT_FK_AST_TYPE ON T_ASS_PROPERTY_TYPE (APT_FK_AST_TYPE ASC)

CREATE TABLE T_ASS_ASSET
(
	ASS_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	ASS_PATHID VARCHAR(200),
	ASS_READABLE VARCHAR(50),
	ASS_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	ASS_ENDTIME datetime2(7) DEFAULT NULL,
	ASS_FK_TEN_TENANT BIGINT NULL ,
	ASS_FK_AST_TYPE BIGINT NOT NULL,
	ASS_FK_ASS_PARTOF BIGINT,
	ASS_LONGITUDE Decimal(9,6) DEFAULT NULL,
	ASS_LATITUDE Decimal(9,6) DEFAULT NULL,
	ASS_LOCALIZATION_TIME datetime2(7) DEFAULT NULL,
	CONSTRAINT PK_ASS_ASSET PRIMARY KEY CLUSTERED (ASS_TECHID),
	CONSTRAINT FK_ASS_FK_TEN_TENANT FOREIGN KEY (ASS_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FKASS_FK_AST_TYPE FOREIGN KEY (ASS_FK_AST_TYPE) REFERENCES T_ASS_ASSET_TYPE(AST_TECHID)
)
CREATE INDEX I_ASS_TECHID ON T_ASS_ASSET (ASS_TECHID ASC)
CREATE INDEX I_ASS_PATHID ON T_ASS_ASSET (ASS_PATHID ASC)
CREATE INDEX I_ASS_FK_AST_TYPE ON T_ASS_ASSET (ASS_FK_AST_TYPE ASC)

CREATE TABLE T_ASS_PROPERTY_VALUE
(
	APV_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	APV_FK_TEN_TENANT BIGINT NULL ,

	APV_FK_APT_TYPE BIGINT NOT NULL,
	APV_FK_ASS_ASSET BIGINT NOT NULL,
	APV_VALUE VARCHAR(4000) NOT NULL, 
    CONSTRAINT PK_APV_TECHID PRIMARY KEY CLUSTERED (APV_TECHID),
	CONSTRAINT FK_APV_FK_APT_TYPE FOREIGN KEY (APV_FK_APT_TYPE) REFERENCES T_ASS_PROPERTY_TYPE(APT_TECHID),
	CONSTRAINT FK_APV_FK_ASS_ASSET FOREIGN KEY (APV_FK_ASS_ASSET) REFERENCES T_ASS_ASSET(ASS_TECHID)
)
CREATE INDEX I_APV_TECHID ON T_ASS_PROPERTY_VALUE (APV_TECHID ASC)
CREATE INDEX I_APV_FK_APT_TYPE ON T_ASS_PROPERTY_VALUE (APV_FK_APT_TYPE ASC)
CREATE INDEX I_APV_FK_ASS_ASSET ON T_ASS_PROPERTY_VALUE (APV_FK_ASS_ASSET ASC)

/*
   -------------------------------- PROVISIONING ----------------------------------------------
*/


CREATE TABLE T_THG_THING_MODEL
(
	THM_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	THM_READABLE VARCHAR(50) DEFAULT NULL,
	THM_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	THM_ENDTIME datetime2(7) DEFAULT NULL,
	THM_FK_TEN_TENANT BIGINT NULL ,
	THM_KIND VARCHAR(30),
	THM_MANUFACTURER VARCHAR(32),
	THM_MODEL VARCHAR(32),
	THM_VERSION VARCHAR(16),
	THM_BEACON_RSSI_1_METER INTEGER,
	THM_MAX_HOURS_INVISIBLE REAL DEFAULT NULL,
	THM_MIN_BATTERY_VOLTAGE REAL DEFAULT NULL,
	THM_MAX_BATTERY_VOLTAGE REAL DEFAULT NULL,

	CONSTRAINT PK_THM_TECHID PRIMARY KEY CLUSTERED (THM_TECHID),
	CONSTRAINT FK_THM_FK_TEN_TENANT FOREIGN KEY (THM_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
)
CREATE INDEX I_T_THM_TYPE_TECHID ON T_THG_THING_MODEL (THM_TECHID ASC)

CREATE TABLE T_THG_THING
(
	THG_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	THG_READABLE VARCHAR(50) DEFAULT NULL,
	THG_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	THG_ENDTIME datetime2(7) DEFAULT NULL,
	THG_FK_TEN_TENANT BIGINT NULL ,
	THG_DISCRIMINATOR VARCHAR(3) NOT NULL,
	THG_FK_THM_MODEL BIGINT NOT NULL,
	THG_FK_ASS_ASSET BIGINT DEFAULT NULL,
	THG_LAST_VISIBLE datetime2(7) DEFAULT NULL,
	THG_MODE VARCHAR(10) DEFAULT 'enabled' NOT NULL,
	BCO_EDDYSTONE_UID VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_UUID VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_MAJOR VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_MINOR VARCHAR(50) DEFAULT NULL,
	LOR_DEV_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_KEY VARCHAR(50) DEFAULT NULL,
	WIF_BSSID VARCHAR(50) DEFAULT NULL,
	WIF_SSID VARCHAR(50) DEFAULT NULL,
	MOB_IMEI VARCHAR(30) DEFAULT NULL,
	TST_SERIAL VARCHAR(30) DEFAULT NULL,
	WST_STATION_ID VARCHAR(50) DEFAULT NULL,
	THG_ROUTE_SIDIM BIT DEFAULT 0,
	CONSTRAINT PK_THG_THING PRIMARY KEY CLUSTERED (THG_TECHID),
	CONSTRAINT FK_THG_FK_TEN_TENANT FOREIGN KEY (THG_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_THG_FK_THM_MODEL FOREIGN KEY (THG_FK_THM_MODEL) REFERENCES T_THG_THING_MODEL(THM_TECHID),
	CONSTRAINT FK_THG_FK_ASS_ASSET FOREIGN KEY (THG_FK_ASS_ASSET) REFERENCES T_ASS_ASSET (ASS_TECHID),
	CONSTRAINT FK_THG_MODE CHECK(THG_MODE IN ('Enabled', 'Disabled', 'Suspended'))
)
CREATE UNIQUE NONCLUSTERED INDEX I_I_LOR_DEV_EUI ON T_THG_THING(LOR_DEV_EUI) WHERE LOR_DEV_EUI IS NOT NULL
CREATE UNIQUE NONCLUSTERED INDEX I_TST_SERIAL ON T_THG_THING(TST_SERIAL) WHERE TST_SERIAL IS NOT NULL
CREATE UNIQUE NONCLUSTERED INDEX I_BCO_IBEACON_UUID ON T_THG_THING(BCO_IBEACON_UUID,BCO_IBEACON_MAJOR,BCO_IBEACON_MINOR) WHERE BCO_IBEACON_UUID IS NOT NULL
CREATE UNIQUE NONCLUSTERED INDEX I_BCO_EDDYSTONE_UID ON T_THG_THING(BCO_EDDYSTONE_UID) WHERE BCO_EDDYSTONE_UID IS NOT NULL
CREATE UNIQUE NONCLUSTERED INDEX I_WIF_BSSID ON T_THG_THING(WIF_BSSID) WHERE WIF_BSSID IS NOT NULL

/*
   -------------------------------- BEACON -----------------------------------------
*/

CREATE TABLE T_BCO_DETECTED
(
	DBC_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	DBC_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	DBC_ENDTIME datetime2(7) DEFAULT NULL,
	DBC_FK_TEN_TENANT BIGINT NULL ,
	DBC_LAST_SCAN_TIME datetime2(7) NOT NULL,
	DBC_LAST_SCAN_DISTANCE REAL NOT NULL,
	DBC_EDDYSTONE_UID VARCHAR(32),
	DBC_FK_THG_GATEWAY BIGINT NOT NULL,
	DBC_FK_THG_BEACON BIGINT NOT NULL,
	CONSTRAINT PK_DBC_TECHID PRIMARY KEY CLUSTERED (DBC_TECHID),
	CONSTRAINT FK_DBC_FK_TEN_TENANT FOREIGN KEY (DBC_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_DBC_FK_THG_GATEWAY FOREIGN KEY (DBC_FK_THG_GATEWAY) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_DBC_FK_THG_BEACON FOREIGN KEY (DBC_FK_THG_BEACON) REFERENCES T_THG_THING(THG_TECHID)
)
CREATE INDEX I_DBC_TECHID ON T_BCO_DETECTED (DBC_TECHID ASC)
CREATE INDEX I_DBC_FK_THG_GATEWAY ON T_BCO_DETECTED (DBC_FK_THG_GATEWAY ASC)
CREATE INDEX I_DBC_FK_THG_BEACON ON T_BCO_DETECTED (DBC_FK_THG_BEACON)

/*
   -------------------------------- TIMESERIES ----------------------------------------------
*/

CREATE TABLE T_TSR_PROVIDER
(
	PRO_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	PRO_REFID VARCHAR(50) NOT NULL,
	PRO_READABLE VARCHAR(50) DEFAULT NULL,
	PRO_PROTOCOL VARCHAR(50) DEFAULT NULL,
	PRO_URL VARCHAR(50) DEFAULT NULL,
	PRO_LOGIN VARCHAR(50) DEFAULT NULL,
	PRO_PASSWORD VARCHAR(50) DEFAULT NULL,
	CONSTRAINT PK_PRO_TECHID PRIMARY KEY CLUSTERED (PRO_TECHID)
)

CREATE INDEX I_PRO_TECHID ON T_TSR_PROVIDER (PRO_TECHID ASC)

CREATE TABLE T_TSR_TIME_SERIE_TYPE
(
	TST_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TST_REFID VARCHAR(50) NOT NULL,
	TST_READABLE VARCHAR(50) DEFAULT NULL,
	TST_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	TST_ENDTIME datetime2(7) DEFAULT NULL,
	TST_FK_TEN_TENANT BIGINT NULL ,
	TST_FORMAT VARCHAR(32) DEFAULT NULL,
	TST_SCHEMA VARCHAR(4000) DEFAULT NULL,
	TST_RELATED_TO_ASSET BIT DEFAULT 1,
	CONSTRAINT FK_TST_FK_TEN_TENANT FOREIGN KEY (TST_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT PK_TST_TECHID PRIMARY KEY CLUSTERED (TST_TECHID),
)
CREATE INDEX I_TST_TECHID ON T_TSR_TIME_SERIE_TYPE (TST_TECHID ASC)
CREATE UNIQUE INDEX I_TST_REFID ON T_TSR_TIME_SERIE_TYPE (TST_REFID ASC)
CREATE INDEX I_TST_FK_TEN_TENANT ON T_TSR_TIME_SERIE_TYPE (TST_FK_TEN_TENANT ASC)

CREATE TABLE T_TSR_TIME_SERIE
(
	TSR_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TSR_FK_TEN_TENANT BIGINT NULL ,
	TSR_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	TSR_ENDTIME datetime2(7) DEFAULT NULL,
	TSR_CURRENT_VALUE_TIME datetime2(7) DEFAULT NULL,
	TSR_DUP_VALUE_TIME datetime2(7) DEFAULT NULL,
	TSR_CURRENT_VALUE VARCHAR(4000) DEFAULT NULL,
	TSR_PROCESSING_STATE VARCHAR(4000) DEFAULT NULL,
	TSR_FK_THG_THING BIGINT NOT NULL,
	TSR_FK_ASS_ASSET BIGINT DEFAULT NULL,
	TSR_FK_TST_TYPE BIGINT DEFAULT NULL,
	CONSTRAINT PK_TSR_TECHID PRIMARY KEY CLUSTERED (TSR_TECHID),
	CONSTRAINT FK_TSR_FK_TEN_TENANT FOREIGN KEY (TSR_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_TSR_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_TSR_FK_ASS_ASSET FOREIGN KEY (TSR_FK_ASS_ASSET) REFERENCES T_ASS_ASSET(ASS_TECHID),
	CONSTRAINT FK_TSR_FK_TST_TYPE FOREIGN KEY (TSR_FK_TST_TYPE) REFERENCES T_TSR_TIME_SERIE_TYPE(TST_TECHID),
)

CREATE INDEX I_TSR_TECHID ON T_TSR_TIME_SERIE (TSR_TECHID ASC)
CREATE INDEX I_TSR_FK_THG_THING ON T_TSR_TIME_SERIE (TSR_FK_TST_TYPE ASC, TSR_FK_THG_THING ASC)

CREATE TABLE T_TSR_TIME_SERIE_POINT
(
	TSP_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TSP_FK_TEN_TENANT BIGINT NULL ,
	TSP_TIME datetime2(7) NOT NULL,
	TSP_VALUE VARCHAR(4000) NOT NULL,
	TSP_FK_TSR_TIME_SERIE BIGINT NOT NULL,
	CONSTRAINT PK_TSP_TECHID PRIMARY KEY CLUSTERED (TSP_TECHID),
	CONSTRAINT FK_TSP_FK_TEN_TENANT FOREIGN KEY (TSP_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_TSP_FK_TSR_TIME_SERIE FOREIGN KEY (TSP_FK_TSR_TIME_SERIE) REFERENCES T_TSR_TIME_SERIE(TSR_TECHID),
)

CREATE INDEX I_TSP_TECHID ON T_TSR_TIME_SERIE_POINT (TSP_TECHID ASC)
CREATE INDEX I_TSP_FK_TSR_TIME_SERIE ON T_TSR_TIME_SERIE_POINT (TSP_FK_TSR_TIME_SERIE ASC, TSP_TIME ASC)


/*------------------------------ ASSET LINKS ----------------------------*/

CREATE TABLE T_PRS_PERSON
(
	PRS_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	PRS_READABLE VARCHAR(50) DEFAULT NULL,
	PRS_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	PRS_ENDTIME datetime2(7) DEFAULT NULL,
	PRS_FK_TEN_TENANT BIGINT NULL ,

	PRS_FIRST_NAME VARCHAR(50) NOT NULL,
	PRS_LAST_NAME VARCHAR(50) NOT NULL,
	PRS_BUSINESS_ROLE VARCHAR(32) NOT NULL,	
	CONSTRAINT PK_PRS_TECHID PRIMARY KEY CLUSTERED (PRS_TECHID),
	CONSTRAINT FK_PRS_FK_TEN_TENANT FOREIGN KEY (PRS_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
)

CREATE INDEX I_PRS_TECHID ON T_PRS_PERSON (PRS_TECHID ASC)

CREATE TABLE T_PRS_ALLOCATION
(
	ALO_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	ALO_BEGTIME datetime2(7) DEFAULT SYSDATETIME ( ),
	ALO_ENDTIME datetime2(7),
	ALO_FK_TEN_TENANT BIGINT NULL ,
	ALO_DISCRIMINATOR VARCHAR(3),
	ALO_FK_PRS_PERSON BIGINT NOT NULL,
	ASA_FK_ASS_ASSET BIGINT DEFAULT NULL,
	ATH_FK_THG_THING BIGINT DEFAULT NULL,

	CONSTRAINT PK_ALO_TECHID PRIMARY KEY CLUSTERED (ALO_TECHID),
	CONSTRAINT FK_ALO_FK_PRS_PERSON FOREIGN KEY (ALO_FK_PRS_PERSON) REFERENCES T_PRS_PERSON(PRS_TECHID),
	CONSTRAINT FK_ALO_FK_TEN_TENANT FOREIGN KEY (ALO_FK_TEN_TENANT) REFERENCES T_TENANT (TEN_TECHID),
	CONSTRAINT FK_ALO_FK_THG_THING FOREIGN KEY (ATH_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
)

CREATE INDEX I_ALO_TECHID ON T_PRS_ALLOCATION (ALO_TECHID ASC)
CREATE INDEX I_ALO_FK_PRS_PERSON ON T_PRS_ALLOCATION (ALO_FK_PRS_PERSON ASC)
CREATE INDEX I_ASA_FK_ASS_ASSET ON T_PRS_ALLOCATION (ASA_FK_ASS_ASSET ASC)

/*---------------------------------- Twins ------------------------------------------*/
CREATE TABLE T_TWI_TWIN_TYPE
(
	TWT_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TWT_BEGTIME DATETIME2(7) DEFAULT NULL,
	TWT_ENDTIME DATETIME2(7) DEFAULT NULL,
	TWT_REFID VARCHAR(64) NOT NULL,

	TWT_FK_TWT_SUPERTYPE BIGINT  DEFAULT NULL,

	CONSTRAINT PK_TWT_TECHID PRIMARY KEY CLUSTERED (TWT_TECHID),
	CONSTRAINT FK_TWT_FK_TWT_SUPERTYPE FOREIGN KEY (TWT_FK_TWT_SUPERTYPE) REFERENCES T_TWI_TWIN_TYPE (TWT_TECHID)
)

CREATE TABLE T_TWI_TWIN
(
	TWI_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TWI_BEGTIME DATETIME2(7) DEFAULT NULL,
	TWI_ENDTIME DATETIME2(7) DEFAULT NULL,
	TWI_DISCRIMINATOR VARCHAR(4) NOT NULL,
	TWI_VALUE VARCHAR(4000) DEFAULT NULL,

	TWI_FK_TWT_TYPE BIGINT  NOT NULL,

	TTH_FK_THG_THING BIGINT DEFAULT NULL,
	TTH_LAST_TIME DATETIME2(7) DEFAULT NULL,

	TAS_FK_ASS_ASSET BIGINT DEFAULT NULL,

	CONSTRAINT PK_TWI_TECHID PRIMARY KEY CLUSTERED (TWI_TECHID),
	CONSTRAINT FK_TWI_FK_TWT_TYPE FOREIGN KEY (TWI_FK_TWT_TYPE) REFERENCES T_TWI_TWIN_TYPE (TWT_TECHID),
	CONSTRAINT FK_TTH_FK_THG_THING FOREIGN KEY (TTH_FK_THG_THING) REFERENCES T_THG_THING (THG_TECHID),
	CONSTRAINT FK_TAS_FK_ASS_ASSET FOREIGN KEY (TAS_FK_ASS_ASSET) REFERENCES T_ASS_ASSET (ASS_TECHID)
)