sql:
   url: jdbc:mariadb://localhost:3306/lasrosasiot
   username: lasrosasiot
   password: lasrosasiot
influxdb:
   server: localhost
   token: 6KZs7VwrEtuXs2RxtL28G9tqcM0zFWQgPm7FIVEYxiIvGxaZ0_0fH1HKsAlkm8PhvbG6kADdWX7VTXIRsBiUcA==
   org: las-rosas.es
   bucket: lasrosasiot
mqtt:
     clientid: ReactorInOutDev
     server: localhost
     persistFolder: target/mqtt-ReactorInOutDev
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: Yes
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        physical_naming_strategy: com.lasrosas.iot.database.UpperCaseNamingStrategy
logging:
 level:
   root: INFO
   org.springframework.orm: INFO
   org.springframework.transaction: INFO
   org.hibernate.engine.transaction.internal.TransactionImpl: INFO
   com.lasrosas.iot.*: DEBUG