name: lasrosasiot-middleware

services:

  database:
    image: postgres:16.3
    container_name: lasrosasiot-database
    shm_size: 128mb
    deploy:
      resources:
        limits:
          memory: 1gb
    environment:
      - POSTGRES_DB=lasrosasiot
      - POSTGRES_USER=lasrosasiot
      - POSTGRES_PASSWORD=lasrosasiot
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/volumes/data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U lasrosasiot -d lasrosasiot"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - lasrosasiot-network
  flyway:
    image: flyway/flyway
    container_name: lasrosasiot-flyway
    command: -url=jdbc:postgresql://lasrosasiot-database:5432/lasrosasiot -schemas=lasrosasiot -user=lasrosasiot -password=lasrosasiot -connectRetries=60 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      database:
        condition: service_healthy
    networks:
      - lasrosasiot-network
  influxdb2:
    image: influxdb:2
    container_name: lasrosasiot-influxdb
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=lasrosasiot
      - DOCKER_INFLUXDB_INIT_PASSWORD=lasrosasiot
      - DOCKER_INFLUXDB_INIT_ORG=lasrosasiot
      - DOCKER_INFLUXDB_INIT_BUCKET=lasrosasiot
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyInitialAdminToken0==
    volumes:
      - ./influxdb/volumes/data:/var/lib/influxdb2
      - ./influxdb/volumes/config:/etc/influxdb2
    healthcheck:
      test: influx ping || exit 1
      interval: 15s
      retries: 5
      start_period: 20s
      timeout: 10s
  grafana:
    image: grafana/grafana-oss
    container_name: lasrosasiot-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=lasrosasiot
      - GF_SECURITY_ADMIN_USER=lasrosasiot
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - '3000:3000'
    depends_on:
      influxdb2:
        condition: service_healthy
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: lasrosasiot-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - MOSQUITTO_USER=lasrosasiot
      - MOSQUITTO_PASSWORD=lasrosasiot
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t healthcheck -m docker-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - lasrosasiot-network
networks:
  lasrosasiot-network:
    # to create the network, run: docker network create lasrosasiot-network
    external: true
