hibernate:
  discriminator:
    ignore_explicit_for_joined:true
influxdb:
   server: localhost
   org: las-rosas.es
   token: 7A4igzhrHx4v6Q9eThnwWAqOv_V996Lq1M4wBi8qE76DvkGkjdU8ITg1z5wtQD9jR1ZIXMW3v3beg22FL_Bd0g==
   bucket: lasrosasiot
rak7249:
  mqtt:
     clientId: lasRosasFluxRak7249Dev
     persistFolder: target/mqtt-rak7249
  connect:
     serverURIs:
       - tcp://@192.168.10.3:1883
publish:
  mqtt:
     clientId: lasRosasFluxLocal
     persistFolder: target/mqtt-localbroker
  connect:
     serverURIs:
       - tcp://@localhost:1883
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lasrosasiot
    username: lasrosasiot
    password: lasrosasiot
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        physical_naming_strategy: com.lasrosas.iot.core.database.LowerCaseNamingStrategy
logging:
  level:
    org.springframework.orm: INFO
    org.springframework.transaction: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    com.lasrosas.iot: DEBUG
