sql:
   url: jdbc:mariadb://localhost:3307/lasrosasiot
   username: lasrosasiot
   password: lasrosasiot
hibernate:
  discriminator:
    ignore_explicit_for_joined:true
influxdb:
   server: localhost
   org: las-rosas.es
   token: xtv9IIwRzk2L9JYYDFHWGILJHmP2cuhc1IOqVfHe4-JuWMEyt2Sgx71sXkPoPtqikBmJrxi17FVbpiWlelImGg==
   bucket: lasrosasiot
rak7249:
  mqtt:
     clientId: lasRosasFluxRak7249Dev
     persistFolder: target/mqtt-rak7249
  connect:
     serverURIs:
       - tcp://@localhost:1883
publish:
  mqtt:
     clientId: lasRosasFluxLocal
     persistFolder: target/mqtt-localbroker
  connect:
     serverURIs:
       - tcp://@localhost:1883
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        physical_naming_strategy: com.lasrosas.iot.core.database.LowerCaseNamingStrategy
logging:
  level:
    org.springframework.orm: INFO
    org.springframework.transaction: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    com.lasrosas.iot: DEBUG
