/*------------------------------------------- DIGITAL_TWIN -------------------------------------------*/

CREATE TABLE T_DTW_SPACE
(
	SPA_TECHID INT UNSIGNED AUTO_INCREMENT,
	SPA_READABLE VARCHAR(50) DEFAULT NULL,

	PRIMARY KEY (SPA_TECHID)
);

CREATE TABLE T_DTW_DIGITAL_TWIN_TYPE
(
	DTY_TECHID INT UNSIGNED AUTO_INCREMENT,
	DTY_READABLE VARCHAR(50) DEFAULT NULL,
	DTY_DISCRIMINATOR VARCHAR(3) NOT NULL,

	DTY_REFID VARCHAR(50) NOT NULL,
	DTY_LOCALIZABLE VARCHAR(10) DEFAULT 'No',
	DTY_FK_SPA_SPACE INT UNSIGNED NOT NULL,
	YTY_FK_DTY_SUPER_TYPE INT UNSIGNED DEFAULT NULL,
	YTY_CONCRETE BIT DEFAULT 1,

	PRIMARY KEY (DTY_TECHID),
	CONSTRAINT FK_YTY_FK_DTY_SUPER_TYPE FOREIGN KEY (YTY_FK_DTY_SUPER_TYPE) REFERENCES T_DTW_DIGITAL_TWIN_TYPE (DTY_TECHID),
	CONSTRAINT FK_DTY_FK_SPA_SPACE FOREIGN KEY (DTY_FK_SPA_SPACE) REFERENCES T_DTW_SPACE (SPA_TECHID)
);


CREATE TABLE T_DTW_DYNAMIC_TWIN_LINK_TYPE
(
	DLT_TECHID INT UNSIGNED AUTO_INCREMENT,

	DLT_FK_DTY_ORIGIN INT UNSIGNED NOT NULL,
	DLT_FK_DTY_DESTINATION INT UNSIGNED NOT NULL,
	DLT_CARD_MIN INTEGER DEFAULT 0,
	DLT_CARD_MAX INTEGER NULL,

	PRIMARY KEY (DLT_TECHID),
	CONSTRAINT FK_DLT_FK_DTY_ORIGIN FOREIGN KEY (DLT_FK_DTY_ORIGIN) REFERENCES T_DTW_DIGITAL_TWIN_TYPE (DTY_TECHID),
	CONSTRAINT FK_DLT_FK_DTY_DESTINATION FOREIGN KEY (DLT_FK_DTY_DESTINATION) REFERENCES T_DTW_DIGITAL_TWIN_TYPE(DTY_TECHID)
);

CREATE TABLE T_DTW_DYNAMIC_TWIN_PROPERTY_TYPE
(
	DPT_TECHID INT UNSIGNED AUTO_INCREMENT,
	DPT_READABLE VARCHAR(50) DEFAULT NULL,

	DPT_FK_DTY_TWIN_TYPE INT UNSIGNED NOT NULL,
	DPT_FORMAT VARCHAR(32) NOT NULL,
    PRIMARY KEY  (DPT_TECHID),
	CONSTRAINT FK_DPT_FK_DTY_TWIN_TYPE FOREIGN KEY (DPT_FK_DTY_TWIN_TYPE) REFERENCES T_DTW_DIGITAL_TWIN_TYPE(DTY_TECHID)
);



CREATE TABLE T_DTW_DIGITAL_TWIN
(
	DTW_TECHID INT UNSIGNED AUTO_INCREMENT,
	DTW_DISCRIMINATOR VARCHAR(3) NOT NULL,
	DTW_PATHID VARCHAR(200),
	DTW_READABLE VARCHAR(50),
	DTW_FK_DTY_TYPE INT UNSIGNED NOT NULL,
	DTW_FK_DTW_PARTOF INT UNSIGNED,
	DTW_LONGITUDE Decimal(9,6) DEFAULT NULL,
	DTW_LATITUDE Decimal(9,6) DEFAULT NULL,
	DTW_LOCALIZATION_TIME datetime DEFAULT NULL,
	PRIMARY KEY (DTW_TECHID),
	CONSTRAINT FK_DTW_FK_DTW_PARTOF FOREIGN KEY (DTW_FK_DTW_PARTOF) REFERENCES T_DTW_DIGITAL_TWIN (DTW_TECHID),
	CONSTRAINT FK_DTW_FK_DTY_TYPE FOREIGN KEY (DTW_FK_DTY_TYPE) REFERENCES T_DTW_DIGITAL_TWIN_TYPE(DTY_TECHID)
);

CREATE TABLE T_DTW_DYNAMIC_TWIN_PROPERTY
(
	DPR_TECHID INT UNSIGNED AUTO_INCREMENT,
	DPR_FK_TEN_TENANT BIGINT NULL ,

	DPR_FK_DPT_TYPE INT UNSIGNED NOT NULL,
	DPR_FK_DTW_TWIN INT UNSIGNED NOT NULL,
	DPR_VALUE VARCHAR(4000) NOT NULL, 
    PRIMARY KEY (DPR_TECHID),
	CONSTRAINT FK_DPR_FK_DPT_TYPE FOREIGN KEY (DPR_FK_DPT_TYPE) REFERENCES T_DTW_DYNAMIC_TWIN_PROPERTY_TYPE(DPT_TECHID),
	CONSTRAINT FK_DPR_FK_DTW_TWIN FOREIGN KEY (DPR_FK_DTW_TWIN) REFERENCES T_DTW_DIGITAL_TWIN(DTW_TECHID)
);

/*
   -------------------------------- PROVISIONING ----------------------------------------------
*/

CREATE TABLE T_THG_GATEWAY
(
	GTW_TECHID INT UNSIGNED AUTO_INCREMENT,
	GTW_REFID VARCHAR(50) NOT NULL,
	GTW_READABLE VARCHAR(50) DEFAULT NULL,
	GTW_PROTOCOL VARCHAR(50) DEFAULT NULL,
	GTW_URL VARCHAR(50) DEFAULT NULL,
	GTW_LOGIN VARCHAR(50) DEFAULT NULL,
	GTW_PASSWORD VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (GTW_TECHID)
);

CREATE TABLE T_THG_THING_TYPE
(
	TTY_TECHID INT UNSIGNED AUTO_INCREMENT,
	TTY_READABLE VARCHAR(50) DEFAULT NULL,
	TTY_DISCRIMINATOR VARCHAR(3),
	TTY_MANUFACTURER VARCHAR(32),
	TTY_MODEL VARCHAR(32),
	TTY_VERSION VARCHAR(16),
	TTY_MAX_HOURS_INVISIBLE REAL DEFAULT NULL,
	TTY_MIN_BATTERY_VOLTAGE REAL DEFAULT NULL,
	TTY_MAX_BATTERY_VOLTAGE REAL DEFAULT NULL,
	BTY_RSSI_1_METER INTEGER,

	PRIMARY KEY (TTY_TECHID)
);

CREATE TABLE T_THG_THING
(
	THG_TECHID INT UNSIGNED AUTO_INCREMENT,
	THG_READABLE VARCHAR(50) DEFAULT NULL,
	THG_DISCRIMINATOR VARCHAR(3) NOT NULL,
	THG_FK_TTY_TYPE INT UNSIGNED NOT NULL,
	THG_FK_DTW_TWIN INT UNSIGNED DEFAULT NULL,
	THG_FK_GTW_GATEWAY INT UNSIGNED,
	THG_LDTY_VISIBLE datetime DEFAULT NULL,
	THG_MODE VARCHAR(10) DEFAULT 'enabled' NOT NULL,
	BCO_EDDYSTONE_UID VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_UUID VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_MAJOR VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_MINOR VARCHAR(50) DEFAULT NULL,
	LOR_DEV_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_KEY VARCHAR(50) DEFAULT NULL,
	WIF_BSSID VARCHAR(50) DEFAULT NULL,
	WIF_SSID VARCHAR(50) DEFAULT NULL,
	MOB_IMEI VARCHAR(30) DEFAULT NULL,
	TST_SERIAL VARCHAR(30) DEFAULT NULL,
	WST_STATION_ID VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (THG_TECHID),
	CONSTRAINT FK_THG_FK_TTY_TYPE FOREIGN KEY (THG_FK_TTY_TYPE) REFERENCES T_THG_THING_TYPE(TTY_TECHID),
	CONSTRAINT FK_THG_FK_DTW_TWIN FOREIGN KEY (THG_FK_DTW_TWIN) REFERENCES T_DTW_DIGITAL_TWIN (DTW_TECHID),
	CONSTRAINT FK_THG_FK_GTW_GATEWAY FOREIGN KEY (THG_FK_GTW_GATEWAY) REFERENCES T_THG_GATEWAY (GTW_TECHID),
	CONSTRAINT FK_THG_MODE CHECK(THG_MODE IN ('Enabled', 'Disabled', 'Suspended'))
);

CREATE TABLE T_THG_SENSOR_TYPE
(
	STY_TECHID INT UNSIGNED AUTO_INCREMENT,
	STY_READABLE VARCHAR(50) DEFAULT NULL,
	STY_FK_TTY_THING_TYPE INT UNSIGNED NOT NULL,

	PRIMARY KEY (STY_TECHID),
	CONSTRAINT FK_STY_FK_TTY_THING_TYPE FOREIGN KEY (STY_FK_TTY_THING_TYPE) REFERENCES T_THG_THING_TYPE(TTY_TECHID)
);

CREATE TABLE T_THG_SENSOR
(
	SEN_TECHID INT UNSIGNED AUTO_INCREMENT,
	SEN_READABLE VARCHAR(50) DEFAULT NULL,
	SEN_FK_STY_TYPE  INT UNSIGNED NOT NULL,
	SEN_FK_THG_THING INT UNSIGNED NOT NULL,

	PRIMARY KEY (SEN_TECHID),
	CONSTRAINT FK_SEN_FK_THG_THING FOREIGN KEY (SEN_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_SEN_FK_STY_TYPE FOREIGN KEY (SEN_FK_STY_TYPE) REFERENCES T_THG_SENSOR_TYPE(STY_TECHID)
);

/*
   -------------------------------- TIMESERIES ----------------------------------------------
*/

CREATE TABLE T_TSR_TIME_SERIE_TYPE
(
	TST_TECHID INT UNSIGNED AUTO_INCREMENT,
	TST_REFID VARCHAR(50) NOT NULL,
	TST_READABLE VARCHAR(50) DEFAULT NULL,
	TST_FORMAT VARCHAR(32) DEFAULT NULL,
	TST_SCHEMA VARCHAR(4000) DEFAULT NULL,
	PRIMARY KEY (TST_TECHID)
);

CREATE TABLE T_TSR_TIME_SERIE
(
	TSR_TECHID INT UNSIGNED AUTO_INCREMENT,
	TSR_FK_THG_THING INT UNSIGNED NOT NULL,
	TSR_FK_DTW_TWIN INT UNSIGNED DEFAULT NULL,
	TSR_FK_TST_TYPE INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (TSR_TECHID),
	CONSTRAINT FK_TSR_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_TSR_FK_DTW_TWIN FOREIGN KEY (TSR_FK_DTW_TWIN) REFERENCES T_DTW_DIGITAL_TWIN (DTW_TECHID),
	CONSTRAINT FK_TSR_FK_TST_TYPE FOREIGN KEY (TSR_FK_TST_TYPE) REFERENCES T_TSR_TIME_SERIE_TYPE(TST_TECHID)
);

