
/* CREATE IMMO ASSET SPACE */
INSERT INTO T_ASS_SPACE (SPA_READABLE) VALUES ('Immobilier')
DECLARE @SPACE_IMMO BIGINT
SET @SPACE_IMMO=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_CONCRETE, AST_FK_SPA_SPACE) VALUES ('BaseImo', 0, @SPACE_IMMO)
DECLARE @IMMO_BASE BIGINT
SET @IMMO_BASE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Site', 1, @SPACE_IMMO, @IMMO_BASE)
DECLARE @IMMO_SITE BIGINT
SET @IMMO_SITE=SCOPE_IDENTITY()

INSERT INTO T_ASS_PROPERTY_TYPE (APT_READABLE, APT_FORMAT, APT_FK_AST_TYPE) VALUES ('Shape', 'Shape', @IMMO_SITE)
DECLARE @IMMO_SHAPE BIGINT
SET @IMMO_SHAPE=SCOPE_IDENTITY()

INSERT INTO T_ASS_PROPERTY_TYPE (APT_READABLE, APT_FORMAT, APT_FK_AST_TYPE) VALUES ('Adresse', 'Adresse', @IMMO_SITE)
DECLARE @IMMO_ADDR BIGINT
SET @IMMO_ADDR=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Floor', 'Etage', 1, @SPACE_IMMO, @IMMO_BASE)
DECLARE @IMMO_ETAGE BIGINT
SET @IMMO_ETAGE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART, ATP_FK_AST_PARTOF, ATP_CARD_MAX) VALUES (@IMMO_ETAGE, @IMMO_SITE, NULL)

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Surface', 1, @SPACE_IMMO, @IMMO_BASE)
DECLARE @IMMO_SURFACE BIGINT
SET @IMMO_SURFACE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART, ATP_FK_AST_PARTOF, ATP_CARD_MAX) VALUES (@IMMO_SURFACE, @IMMO_ETAGE, NULL)
INSERT INTO T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART, ATP_FK_AST_PARTOF, ATP_CARD_MAX) VALUES (@IMMO_SURFACE, @IMMO_SITE, NULL)

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Room', 'Piece', 0, @SPACE_IMMO, @IMMO_BASE)
DECLARE @IMMO_PIECE BIGINT
SET @IMMO_PIECE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Office', 'Bureau', 1, @SPACE_IMMO, @IMMO_PIECE)
DECLARE @IMMO_BUREAU BIGINT
SET @IMMO_BUREAU=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART, ATP_FK_AST_PARTOF, ATP_CARD_MAX) VALUES (@IMMO_BUREAU, @IMMO_SURFACE, NULL)
INSERT INTO T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART, ATP_FK_AST_PARTOF, ATP_CARD_MAX) VALUES (@IMMO_BUREAU, @IMMO_ETAGE, NULL)
INSERT INTO T_ASS_ASSET_TYPE_PART (ATP_FK_AST_PART, ATP_FK_AST_PARTOF, ATP_CARD_MAX) VALUES (@IMMO_BUREAU, @IMMO_SITE, NULL)

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('CAC', @IMMO_SITE)
DECLARE @IMMO_CAC BIGINT
SET @IMMO_CAC=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('Etage 1', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E1 BIGINT
SET @IMMO_CAC_E1=SCOPE_IDENTITY()

INSERT INTO T_ASS_PROPERTY_VALUE (APV_FK_APT_TYPE, APV_FK_ASS_ASSET, APV_VALUE) VALUES (@IMMO_SHAPE, @IMMO_CAC, '46.185809,6.144026|46.185568,6.143913|46.185423,6.144412|46.185055,6.144246|46.185174,6.143629|46.185259,6.143661|46.185456,6.142964|46.186019,6.143267|46.185809,6.144026')

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('2', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E2 BIGINT
SET @IMMO_CAC_E2=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('3', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E3 BIGINT
SET @IMMO_CAC_E3=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('4', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E4 BIGINT
SET @IMMO_CAC_E4=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('5', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E5 BIGINT
SET @IMMO_CAC_E5=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('6', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E6 BIGINT
SET @IMMO_CAC_E6=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('7', @IMMO_ETAGE, @IMMO_CAC)
DECLARE @IMMO_CAC_E7 BIGINT
SET @IMMO_CAC_E7=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('DEX', @IMMO_SURFACE, @IMMO_CAC_E7)
DECLARE @IMMO_CAC_E7_DEX BIGINT
SET @IMMO_CAC_E7_DEX=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('7.19', @IMMO_BUREAU, @IMMO_CAC_E7_DEX)
DECLARE @IMMO_BUR7_19 BIGINT
SET @IMMO_BUR7_19=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('7.21', @IMMO_BUREAU, @IMMO_CAC_E7_DEX)
DECLARE @IMMO_BUR7_21 BIGINT
SET @IMMO_BUR7_21=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_FK_ASS_PARTOF) VALUES ('7.22', @IMMO_BUREAU, @IMMO_CAC_E7_DEX)
DECLARE @IMMO_BUR7_22 BIGINT
SET @IMMO_BUR7_22=SCOPE_IDENTITY()

DECLARE @LAST_SITE BIGINT
INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_LATITUDE, ASS_LONGITUDE) VALUES ('Plan les ouates', @IMMO_SITE, 46.185642, 6.143487)
SET @LAST_SITE=SCOPE_IDENTITY()
INSERT INTO T_ASS_PROPERTY_VALUE (APV_FK_APT_TYPE, APV_FK_ASS_ASSET, APV_VALUE) VALUES (@IMMO_ADDR, @LAST_SITE, 'Chemin de Vers 8, Plan-Les-Ouates')

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_LATITUDE, ASS_LONGITUDE) VALUES ('Petit Lancy', @IMMO_SITE, 46.189523, 6.116525)
SET @LAST_SITE=SCOPE_IDENTITY()
INSERT INTO T_ASS_PROPERTY_VALUE (APV_FK_APT_TYPE, APV_FK_ASS_ASSET, APV_VALUE) VALUES (@IMMO_ADDR, @LAST_SITE, 'Chemin des Clochetons 1, Petit-Lancy')

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_LATITUDE, ASS_LONGITUDE) VALUES ('Carl-Vogt', @IMMO_SITE, 46.200980, 6.13034)
SET @LAST_SITE=SCOPE_IDENTITY()
INSERT INTO T_ASS_PROPERTY_VALUE (APV_FK_APT_TYPE, APV_FK_ASS_ASSET, APV_VALUE) VALUES (@IMMO_ADDR, @LAST_SITE, 'Boulevard Carl-Vogt 2, Genève')

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE, ASS_LATITUDE, ASS_LONGITUDE) VALUES ('Pont d''Arves', @IMMO_SITE, 46.195233, 6.142448)
SET @LAST_SITE=SCOPE_IDENTITY()
INSERT INTO T_ASS_PROPERTY_VALUE (APV_FK_APT_TYPE, APV_FK_ASS_ASSET, APV_VALUE) VALUES (@IMMO_ADDR, @LAST_SITE, 'Boulevard du Pont-d''Arve 28, Genève')


/* CREATE VEHICULES ASSET SPACE */
INSERT INTO T_ASS_SPACE (SPA_READABLE) VALUES ('Véhicule')
DECLARE @SPACE_VEHI BIGINT
SET @SPACE_VEHI=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_CONCRETE, AST_FK_SPA_SPACE) VALUES ('BaseVehicule', 0, @SPACE_VEHI)
DECLARE @VEHI_BASE BIGINT
SET @VEHI_BASE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Car', 'Voiture', 1, @SPACE_VEHI, @VEHI_BASE)
DECLARE @VEHI_VOIT BIGINT
SET @VEHI_VOIT=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Ebike', 'VAE', 1, @SPACE_VEHI, @VEHI_BASE)
DECLARE @VEHI_VAE BIGINT
SET @VEHI_VAE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Bicycle', 'Vélo', 1, @SPACE_VEHI, @VEHI_BASE)
DECLARE @VEHI_VELO BIGINT
SET @VEHI_VELO=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('Bike', 'Scooter', 1, @SPACE_VEHI, @VEHI_BASE)
DECLARE @VEHI_SCOOTER BIGINT
SET @VEHI_SCOOTER=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('121', @VEHI_VOIT)
DECLARE @VOIT121 BIGINT
SET @VOIT121=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('121', @VEHI_VOIT)
DECLARE @VOIT122 BIGINT
SET @VOIT122=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('001', @VEHI_VAE)
DECLARE @VAE001 BIGINT
SET @VAE001=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('002', @VEHI_VAE)
DECLARE @VAE002 BIGINT
SET @VAE002=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('003', @VEHI_VAE)
DECLARE @VAE003 BIGINT
SET @VAE003=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('001', @VEHI_VELO)
DECLARE @VELO001 BIGINT
SET @VELO001=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('002', @VEHI_VELO)
DECLARE @VELO002 BIGINT
SET @VELO002=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('003', @VEHI_VELO)
DECLARE @VELO003 BIGINT
SET @VELO003=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET (ASS_READABLE, ASS_FK_AST_TYPE) VALUES ('Scoot de Tibo', @VEHI_SCOOTER)
DECLARE @SCOOTTIBO BIGINT
SET @SCOOTTIBO=SCOPE_IDENTITY()

/* CREATE VEHICULES ASSET SPACE */
INSERT INTO T_ASS_SPACE (SPA_READABLE) VALUES ('Logistique')
DECLARE @SPACE_LOGI BIGINT
SET @SPACE_LOGI=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_CONCRETE, AST_FK_SPA_SPACE) VALUES ('BaseLogistique', 0, @SPACE_LOGI)
DECLARE @LOGI_BASE BIGINT
SET @LOGI_BASE=SCOPE_IDENTITY()

INSERT INTO T_ASS_ASSET_TYPE (AST_REFID, AST_READABLE, AST_CONCRETE, AST_FK_SPA_SPACE, AST_FK_AST_SUPER_TYPE) VALUES ('BlueBox', 'Boite bleue', 1, @SPACE_LOGI, @VEHI_BASE)
DECLARE @LOGI_BB BIGINT
SET @LOGI_BB=SCOPE_IDENTITY()

/* CREATE WIFI THINGS*/
INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND) VALUES ('Wifi', 'Wifi')
DECLARE @WIFI BIGINT
SET @WIFI=SCOPE_IDENTITY()

DECLARE @THING BIGINT

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET, THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '0:26:3e:6f:e1:80', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '0:26:3e:6f:e1:82', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:6f:f1:c0', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:6f:f1:c2', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:70:31:c0', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:70:31:c2', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:70:b1:00', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:70:b1:02', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:71:6b:c0', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:71:6b:c2', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:71:96:c0', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:71:96:c2', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:72:70:40', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:72:70:42', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4a:d5:40', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4a:d5:42', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4a:d8:80', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4a:d8:82', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4a:d9:80', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4a:d9:82', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4b:16:c0', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '3c:8a:b0:4b:16:c2', 'wimad')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', 'f8:c0:01:a2:41:40', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', 'f8:c0:01:a2:41:42', 'wimad')


INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:71:97:40', 'wimadguest')

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET,THG_DISCRIMINATOR, WIF_BSSID, WIF_SSID) VALUES (@WIFI, @IMMO_CAC, 'WIF', '00:26:3e:71:97:42', 'wimad')


INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND) VALUES ('Samsung S5', 'Mobile')
DECLARE @MOBILE BIGINT
SET @MOBILE=SCOPE_IDENTITY()


INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_READABLE, THG_DISCRIMINATOR, MOB_IMEI) VALUES (@MOBILE, 'Téléphone de Thibault', 'MOB', '354607086785734')


INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND, THM_MANUFACTURER, THM_MODEL) VALUES ('B&B standard', 'Beacon', 'BnB', 'Standard')
DECLARE @BnbStd BIGINT
SET @BnbStd=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, BCO_EDDYSTONE_UID) VALUES (@BnbStd, 'BCO',  'afa87cbdb5441ef94e001001')
DECLARE @BnbStd001 BIGINT
SET @BnbStd001=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, BCO_EDDYSTONE_UID) VALUES (@BnbStd, 'BCO', 'afa87cbdb5441ef94e001002')
DECLARE @BnbStd002 BIGINT
SET @BnbStd002=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, BCO_EDDYSTONE_UID) VALUES (@BnbStd, 'BCO', 'afa87cbdb5441ef94e001003')
DECLARE @BnbStd003 BIGINT
SET @BnbStd003=SCOPE_IDENTITY()


INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND, THM_MANUFACTURER, THM_MODEL) VALUES ('B&B plus', 'Beacon', 'BnB', 'Plus')
DECLARE @BnbPlus BIGINT
SET @BnbPlus=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, BCO_EDDYSTONE_UID) VALUES (@BnbPlus, 'BCO', 'afa87cbdb5441ef94e002001')
DECLARE @BnBPlus001 BIGINT
SET @BnBPlus001=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, BCO_EDDYSTONE_UID) VALUES (@BnbPlus, 'BCO', 'afa87cbdb5441ef94e002002')
DECLARE @BnBPlus002 BIGINT
SET @BnBPlus002=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, BCO_EDDYSTONE_UID) VALUES (@BnbPlus, 'BCO', 'afa87cbdb5441ef94e002003')
DECLARE @BnBPlus003 BIGINT
SET @BnBPlus003=SCOPE_IDENTITY()



INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND, THM_MANUFACTURER, THM_MODEL) VALUES ('ADN-ARF8123AA', 'Lora', 'ADENUIS', 'ARF8123AA')
DECLARE @ThingMod BIGINT
SET @ThingMod=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, LOR_DEV_EUI, LOR_APP_EUI, LOR_APP_KEY) VALUES (@ThingMod, 'LOR', '0018B20000002309', '0018B24441524632', 'BE0331C63844166093A8A8E3A11A6970')

INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND, THM_MANUFACTURER, THM_MODEL) VALUES ('ADN-ARF8180BA', 'Lora', 'ADENUIS', 'ARF8180BAB')
SET @ThingMod=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_DISCRIMINATOR, LOR_DEV_EUI, LOR_APP_EUI, LOR_APP_KEY) VALUES (@ThingMod, 'LOR', '0018B2200000093C', '0018B254454D5031', 'A2F47FE01562A61E3C88E07E5F6C0E0B')


INSERT INTO T_TSR_PROVIDER (PRO_REFID, PRO_READABLE, PRO_PROTOCOL, PRO_URL, PRO_LOGIN, PRO_PASSWORD)
		VALUES('SIG', 'Réseau LORA des SIG', 'lora', 'https://lora-ns.sig-ge.ch', 'imad_test', '8Qtx-JURA-ucYL-mhdh')
DECLARE @ProSIG BIGINT
SET @ProSIG=SCOPE_IDENTITY()

INSERT INTO T_TSR_PROVIDER (PRO_REFID, PRO_READABLE, PRO_PROTOCOL)
		VALUES('TEST', 'Lora provider de test', 'test')
DECLARE @ProTEST BIGINT
SET @ProTEST=SCOPE_IDENTITY()

INSERT INTO T_TSR_PROVIDER (PRO_REFID, PRO_READABLE, PRO_PROTOCOL)
		VALUES('openweathermap.org', 'openweathermap.org', 'wst')
DECLARE @ProWeather BIGINT
SET @ProWeather=SCOPE_IDENTITY()

/* ONTHOOGY */
INSERT INTO T_TSR_TIME_SERIE_TYPE (TST_REFID, TST_FORMAT, TST_SCHEMA) VALUES ('indoorEnvironmentObserved', 'json', 'IndoorEnvironmentObserved')
DECLARE @IndoorEnvObs BIGINT
SET @IndoorEnvObs=SCOPE_IDENTITY()

INSERT INTO T_TSR_TIME_SERIE_TYPE (TST_REFID, TST_FORMAT, TST_SCHEMA) VALUES ('weatherObserved', 'json', 'WeatherObserved')
DECLARE @WeatherObs BIGINT
SET @WeatherObs=SCOPE_IDENTITY()

/* Weather Station */
insert into T_THG_THING_MODEL (THM_KIND, THM_BEGTIME, THM_MANUFACTURER, THM_MODEL, THM_READABLE) VALUES('WST', SYSDATETIME ( ), 'openweathermap.org', 'API-2.5', 'Weather Sation')
DECLARE @ThingModWst BIGINT
SET @ThingModWst=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_BEGTIME, THG_DISCRIMINATOR, WST_STATION_ID, THG_READABLE) VALUES (@ThingModWst, SYSDATETIME ( ), 'WST', 'Geneva', 'Geneva Weather Sation')

/* TEST SENSORS */

INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND, THM_MANUFACTURER, THM_MODEL) VALUES ('IMAD-TEST001', 'Test', 'IMAD', 'A')
DECLARE @ThingModImadA BIGINT
SET @ThingModImadA=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_READABLE, THG_FK_ASS_ASSET, THG_DISCRIMINATOR, TST_SERIAL) VALUES (@ThingModImadA, 'TST-001', @IMMO_BUR7_19, 'TST', '001')
DECLARE @ThingImadA01 BIGINT
SET @ThingImadA01=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_READABLE, THG_FK_ASS_ASSET, THG_DISCRIMINATOR, TST_SERIAL) VALUES (@ThingModImadA, 'TST-002', @IMMO_BUR7_19, 'TST', '002')
DECLARE @ThingImadA02 BIGINT
SET @ThingImadA02=SCOPE_IDENTITY()

INSERT INTO T_THG_THING_MODEL (THM_READABLE, THM_KIND, THM_MANUFACTURER, THM_MODEL) VALUES ('IMAD-TEST001', 'Test', 'IMAD', 'B')
DECLARE @ThingModImadB BIGINT
SET @ThingModImadB=SCOPE_IDENTITY()

INSERT INTO T_THG_THING (THG_FK_THM_MODEL, THG_FK_ASS_ASSET, THG_DISCRIMINATOR, TST_SERIAL) VALUES (@ThingModImadB, @IMMO_BUR7_19, 'TST', '003')
DECLARE @ThingImadB01 BIGINT
SET @ThingImadB01=SCOPE_IDENTITY()

/* Test thing data */
INSERT INTO T_TSR_TIME_SERIE (TSR_FK_THG_THING, TSR_FK_TST_TYPE, TSR_FK_PRO_PROVIDER) VALUES (@ThingImadA01, @IndoorEnvObs, @ProTest)
DECLARE @ThingImadA01IndoorEnvObs BIGINT
SET @ThingImadA01IndoorEnvObs=SCOPE_IDENTITY()

INSERT INTO T_TSR_TIME_SERIE_POINT (TSP_FK_TSR_TIME_SERIE, TSP_TIME, TSP_VALUE) VALUES
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:00:00 AM', 5), '{"temperature":20.3,"humidity":40.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:01:00 AM', 5), '{"temperature":21.3,"humidity":41.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:02:00 AM', 5), '{"temperature":22.3,"humidity":42.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:03:00 AM', 5), '{"temperature":23.3,"humidity":43.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:04:00 AM', 5), '{"temperature":24.3,"humidity":44.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:05:00 AM', 5), '{"temperature":25.3,"humidity":45.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:06:00 AM', 5), '{"temperature":26.3,"humidity":46.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:07:00 AM', 5), '{"temperature":27.3,"humidity":47.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:08:00 AM', 5), '{"temperature":28.3,"humidity":48.2}'),
	(@ThingImadA01IndoorEnvObs, convert(datetime,'01-06-18 01:09:00 AM', 5), '{"temperature":29.3,"humidity":49.2}')

INSERT INTO T_TSR_TIME_SERIE (TSR_FK_THG_THING, TSR_FK_TST_TYPE, TSR_FK_PRO_PROVIDER) VALUES (@ThingImadA01, @WeatherObs, @ProTest)
DECLARE @ThingImadA01WeatherObs BIGINT
SET @ThingImadA01WeatherObs=SCOPE_IDENTITY()

INSERT INTO T_TSR_TIME_SERIE_POINT (TSP_FK_TSR_TIME_SERIE, TSP_TIME, TSP_VALUE) VALUES
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:00:00 AM', 5), '{"temperature":10.3,"humidity":60.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:01:00 AM', 5), '{"temperature":11.3,"humidity":61.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:02:00 AM', 5), '{"temperature":12.3,"humidity":62.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:03:00 AM', 5), '{"temperature":13.3,"humidity":63.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:04:00 AM', 5), '{"temperature":14.3,"humidity":64.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:05:00 AM', 5), '{"temperature":15.3,"humidity":65.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:06:00 AM', 5), '{"temperature":16.3,"humidity":66.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:07:00 AM', 5), '{"temperature":17.3,"humidity":67.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:08:00 AM', 5), '{"temperature":18.3,"humidity":68.2}'),
	(@ThingImadA01WeatherObs, convert(datetime,'01-06-18 01:09:00 AM', 5), '{"temperature":19.3,"humidity":69.2}')

INSERT INTO T_TSR_TIME_SERIE (TSR_FK_THG_THING, TSR_FK_TST_TYPE, TSR_FK_PRO_PROVIDER) VALUES (@ThingImadA02, @IndoorEnvObs, @ProTest)
DECLARE @ThingImadA02IndoorEnvObs BIGINT
SET @ThingImadA02IndoorEnvObs=SCOPE_IDENTITY()

INSERT INTO T_TSR_TIME_SERIE_POINT (TSP_FK_TSR_TIME_SERIE, TSP_TIME, TSP_VALUE) VALUES
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:00:00 AM', 5), '{"temperature":30.3,"humidity":50.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:01:00 AM', 5), '{"temperature":31.3,"humidity":51.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:02:00 AM', 5), '{"temperature":32.3,"humidity":52.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:03:00 AM', 5), '{"temperature":33.3,"humidity":53.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:04:00 AM', 5), '{"temperature":34.3,"humidity":54.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:05:00 AM', 5), '{"temperature":35.3,"humidity":55.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:06:00 AM', 5), '{"temperature":36.3,"humidity":56.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:07:00 AM', 5), '{"temperature":37.3,"humidity":57.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:08:00 AM', 5), '{"temperature":38.3,"humidity":58.2}'),
	(@ThingImadA02IndoorEnvObs, convert(datetime,'01-06-18 01:09:00 AM', 5), '{"temperature":39.3,"humidity":59.2}')

/*----- Twins ----------------*/
	
INSERT INTO T_TWI_TWIN_TYPE (TWT_BEGTIME, TWT_REFID) VALUES (convert(datetime,'01-06-18 01:00:00 AM', 5), 'Default')
DECLARE @TWT_DEFAULT BIGINT
SET @TWT_DEFAULT=SCOPE_IDENTITY()

INSERT INTO T_TWI_TWIN (TWI_BEGTIME, TWI_ENDTIME, TWI_DISCRIMINATOR, TWI_FK_TWT_TYPE, TWI_VALUE, TAS_FK_ASS_ASSET)
SELECT ass.ASS_BEGTIME, ass.ASS_ENDTIME, 'ASS', @TWT_DEFAULT, '{}', ass.ASS_TECHID FROM T_ASS_ASSET ass WHERE (SELECT COUNT(*) FROM T_TWI_TWIN twi WHERE twi.TAS_FK_ASS_ASSET = ass.ASS_TECHID) = 0

INSERT INTO T_TWI_TWIN (TWI_BEGTIME, TWI_ENDTIME, TWI_DISCRIMINATOR, TWI_FK_TWT_TYPE, TWI_VALUE, TTH_FK_THG_THING)
SELECT thg.THG_BEGTIME, thg.THG_ENDTIME, 'THG', @TWT_DEFAULT, '{}', thg.THG_TECHID FROM T_THG_THING thg WHERE (SELECT COUNT(*) FROM T_TWI_TWIN twi WHERE twi.TTH_FK_THG_THING = thg.THG_TECHID) = 0


