DELETE FROM choses.T_BCO_BEACON_SCAN
DBCC CHECKIDENT ('choses.T_BCO_BEACON_SCAN', RESEED, 0)

DELETE FROM choses.T_BCO_DETECTED_BEACON
DBCC CHECKIDENT ('choses.T_BCO_DETECTED_BEACON', RESEED, 0)

DELETE FROM choses.T_TS_POINT
DBCC CHECKIDENT ('choses.T_TS_POINT', RESEED, 0)

DELETE FROM choses.T_TS_NETWORK
DBCC CHECKIDENT ('choses.T_TS_NETWORK', RESEED, 0)

DELETE FROM choses.T_TS_GEOLOC
DBCC CHECKIDENT ('choses.T_TS_GEOLOC', RESEED, 0)

DELETE FROM choses.T_TS_TIME_SERIE_CHANNEL
DBCC CHECKIDENT ('choses.T_TS_TIME_SERIE_CHANNEL', RESEED, 0)

DELETE FROM choses.T_TS_TIME_SERIE_TYPE
DBCC CHECKIDENT ('choses.T_TS_TIME_SERIE_TYPE', RESEED, 0)

DELETE FROM choses.T_THG_PROPERTY_VALUE
DBCC CHECKIDENT ('choses.T_THG_PROPERTY_VALUE', RESEED, 0)

DELETE FROM choses.T_THG_THING
DBCC CHECKIDENT ('choses.T_THG_THING', RESEED, 0)

DELETE FROM choses.T_THG_THING_TYPE_PROPERTY
DBCC CHECKIDENT ('choses.T_THG_THING_TYPE_PROPERTY', RESEED, 0)

DELETE FROM choses.T_THG_THING_TYPE
DBCC CHECKIDENT ('choses.T_THG_THING_TYPE', RESEED, 0)

DELETE FROM choses.T_PLC_PLACE
DBCC CHECKIDENT ('choses.T_PLC_PLACE', RESEED, 0)

DELETE FROM choses.T_PLC_PLACE_TYPE
DBCC CHECKIDENT ('choses.T_PLC_PLACE_TYPE', RESEED, 0)

DELETE FROM choses.T_SYN_TABLE

DROP TABLE choses.T_TS_NETWORK
DROP TABLE choses.T_TS_GEOLOC
DROP TABLE choses.T_TS_POINT
DROP TABLE choses.T_BCO_BEACON_SCAN
DROP TABLE choses.T_BCO_DETECTED_BEACON
DROP TABLE choses.T_TS_TIME_SERIE_CHANNEL
DROP TABLE choses.T_TS_TIME_SERIE_TYPE
DROP TABLE choses.T_THG_PROPERTY_VALUE
DROP TABLE choses.T_THG_THING
DROP TABLE choses.T_THG_THING_TYPE_PROPERTY
DROP TABLE choses.T_THG_THING_TYPE
DROP TABLE choses.T_PLC_PLACE
DROP TABLE choses.T_PLC_PLACE_TYPE
DROP TABLE choses.T_SYN_TABLE
DROP TABLE choses.T_SCHEMA_VERSION

/*
   -------------------------------- PLACES ----------------------------------------------
*/
CREATE TABLE choses.T_PLC_PLACE_TYPE
(
	PLT_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	PLT_NAME VARCHAR(50) NOT NULL,
	PLT_OFFICE BIT NOT NULL,
	CONSTRAINT PK_PLT_TECHID PRIMARY KEY CLUSTERED (PLT_TECHID)
)

CREATE TABLE choses.T_PLC_PLACE
(
	PLC_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	PLC_REFID VARCHAR(50) NOT NULL,
	PLC_NAME VARCHAR(50) NOT NULL,
	PLC_LONGITUDE REAL NOT NULL,
	PLC_LATITUDE REAL NOT NULL,
	PLC_SHAPE VARCHAR(500),
	PLC_FK_PLT_TYPE BIGINT NOT NULL,

	CONSTRAINT PK_PLC_TECHIDX PRIMARY KEY CLUSTERED (PLC_TECHID),
	CONSTRAINT FK_PLC_FK_PLT_TYPE FOREIGN KEY (PLC_FK_PLT_TYPE) REFERENCES choses.T_PLC_PLACE_TYPE(PLT_TECHID)
)

CREATE INDEX I_PLC_TECHID ON choses.T_PLC_PLACE (PLC_TECHID ASC)
CREATE INDEX I_PLC_REFID ON choses.T_PLC_PLACE (PLC_REFID ASC)
CREATE INDEX I_PLC_FK_PLT_TYPE ON choses.T_PLC_PLACE (PLC_FK_PLT_TYPE ASC)


/*
   -------------------------------- SYNCHRO ----------------------------------------------
*/
CREATE TABLE choses.T_SYN_TABLE
(
	STA_TABLE VARCHAR(50) NOT NULL,
	STA_LAST_UPDATE DATETIME NOT NULL,

	CONSTRAINT PKT_SYN_TABLE PRIMARY KEY CLUSTERED ([STA_TABLE])
)

/*
   -------------------------------- THINGS ----------------------------------------------
*/
CREATE TABLE choses.T_THG_THING_TYPE
(
	TGT_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TGT_NAME VARCHAR(50) NOT NULL
	CONSTRAINT PK_TGT_TECHID PRIMARY KEY CLUSTERED (TGT_TECHID)
)
CREATE INDEX I_T_THG_TYPE_TECHID ON choses.T_THG_THING_TYPE (TGT_TECHID ASC)


CREATE TABLE choses.T_THG_THING_TYPE_PROPERTY
(
	TTP_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TTP_FK_TGT_TYPE BIGINT NOT NULL,
	TTP_NAME VARCHAR(50) NOT NULL, 
    CONSTRAINT PK_TTP_TECHID PRIMARY KEY CLUSTERED (TTP_TECHID),
	CONSTRAINT FK_TTP_FK_TGT_TYPE FOREIGN KEY (TTP_FK_TGT_TYPE) REFERENCES choses.T_THG_THING_TYPE(TGT_TECHID)
)
CREATE INDEX I_TTP_TECHID ON choses.T_THG_THING_TYPE_PROPERTY (TTP_TECHID ASC)
CREATE INDEX I_FK_TTP_FK_TGT_TYPE ON choses.T_THG_THING_TYPE (TGT_TECHID ASC)


CREATE TABLE choses.T_THG_THING
(
	THG_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	THG_REFID VARCHAR(50) NOT NULL,
	THG_FK_TGT_TYPE BIGINT NOT NULL,
	THG_LINK_REFID VARCHAR(50),
	CONSTRAINT PK_THG_THING PRIMARY KEY CLUSTERED (THG_TECHID),
	CONSTRAINT FK_THG_FK_TGT_TYPE FOREIGN KEY (THG_FK_TGT_TYPE) REFERENCES choses.T_THG_THING_TYPE(TGT_TECHID)
)
CREATE INDEX I_THG_TECHID ON choses.T_THG_THING (THG_TECHID ASC)
CREATE INDEX I_THG_REFID ON choses.T_THG_THING (THG_REFID ASC)
CREATE INDEX I_THG_FK_TGT_TYPE ON choses.T_THG_THING (THG_FK_TGT_TYPE ASC)
CREATE INDEX I_THG_LINK_REFID ON choses.T_THG_THING (THG_LINK_REFID ASC)


CREATE TABLE choses.T_THG_PROPERTY_VALUE
(
	TPV_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TPV_FK_TTP_TYPE BIGINT NOT NULL,
	TPV_FK_THG_THING BIGINT NOT NULL,
	TPV_VALUE VARCHAR(50) NOT NULL, 
    CONSTRAINT PK_TPV_TECHID PRIMARY KEY CLUSTERED (TPV_TECHID),
	CONSTRAINT FK_TPV_FK_TGT_TYPE FOREIGN KEY (TPV_FK_TTP_TYPE) REFERENCES choses.T_THG_THING_TYPE_PROPERTY(TTP_TECHID),
	CONSTRAINT FK_TPV_FK_THG_THING FOREIGN KEY (TPV_FK_THG_THING) REFERENCES choses.T_THG_THING(THG_TECHID)
)
CREATE INDEX I_TPV_TECHID ON choses.T_THG_PROPERTY_VALUE (TPV_TECHID ASC)
CREATE INDEX I_TTP_FK_TGT_TYPE ON choses.T_THG_THING_TYPE_PROPERTY (TTP_TECHID ASC)
CREATE INDEX I_TPV_FK_THG_THING ON choses.T_THG_THING (THG_TECHID ASC)

/*
   -------------------------------- BEACON INVENTORY -----------------------------------------
*/

CREATE TABLE choses.T_BCO_DETECTED_BEACON
(
	DBC_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	DBC_BEGAT DATETIME NOT NULL,
	DBC_LAST_SCAN_DATETIME DATETIME NOT NULL,
	DBC_LAST_SCAN_DISTANCE REAL NOT NULL,
	DBC_ENDAT DATETIME,
	DBC_EDDYSTONE_UID VARCHAR(25),
	DBC_END_OF_SCAN INT,
	DBC_FK_THG_GATEWAY BIGINT NOT NULL,
	DBC_FK_THG_BEACON BIGINT NOT NULL,
	CONSTRAINT PK_DBC_TECHID PRIMARY KEY CLUSTERED (DBC_TECHID),
	CONSTRAINT FK_DBC_FK_THG_GATEWAY FOREIGN KEY (DBC_FK_THG_GATEWAY) REFERENCES choses.T_THG_THING(THG_TECHID),
	CONSTRAINT FK_DBC_FK_THG_BEACON FOREIGN KEY (DBC_FK_THG_BEACON) REFERENCES choses.T_THG_THING(THG_TECHID)
)
CREATE INDEX I_DBC_TECHID ON choses.T_BCO_DETECTED_BEACON (DBC_TECHID ASC)
CREATE INDEX I_DBC_FK_THG_GATEWAY ON choses.T_BCO_DETECTED_BEACON (DBC_FK_THG_GATEWAY ASC)
CREATE INDEX I_DBC_FK_THG_BEACON ON choses.T_BCO_DETECTED_BEACON (DBC_FK_THG_BEACON)

CREATE TABLE choses.T_BCO_BEACON_SCAN
(
	BCS_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	BCS_BEGAT DATETIME NOT NULL,
	BCS_ENDAT DATETIME,
	BCS_DISTANCE_AVG REAL NOT NULL,
	BCS_DISTANCE_MIN REAL NOT NULL,
	BCS_DISTANCE_MAX REAL NOT NULL,
	BCS_LONGITUDE REAL,
	BCS_LATITUDE REAL,
	BCS_ACCURACY REAL,
	BCS_FK_DBC_DETECTED_BEACON BIGINT NOT NULL,
	BCS_FK_PLC_PLACE BIGINT NULL,
	CONSTRAINT PK_BCS_TECHID PRIMARY KEY CLUSTERED (BCS_TECHID),
	CONSTRAINT FK_BCS_FK_PLC_PLACE FOREIGN KEY (BCS_FK_PLC_PLACE) REFERENCES choses.T_PLC_PLACE(PLC_TECHID),
	CONSTRAINT FK_BCS_FK_DBC_DETECTED_BEACON FOREIGN KEY (BCS_FK_DBC_DETECTED_BEACON) REFERENCES choses.T_BCO_DETECTED_BEACON(DBC_TECHID)
)

CREATE INDEX I_BCS_TECHID ON choses.T_BCO_BEACON_SCAN (BCS_TECHID ASC)
CREATE INDEX I_BCS_FK_BCO_DETECTED_BEACON ON choses.T_BCO_DETECTED_BEACON (DBC_TECHID ASC)


/*
   -------------------------------- TIMESERIES ----------------------------------------------
*/
CREATE TABLE choses.T_TS_TIME_SERIE_TYPE
(
	TST_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TST_REFID VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TST_TECHID PRIMARY KEY CLUSTERED (TST_TECHID)
)
CREATE INDEX I_TST_TECHID ON choses.T_TS_TIME_SERIE_TYPE (TST_TECHID ASC)

CREATE TABLE choses.T_TS_TIME_SERIE_CHANNEL
(
	TSC_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TSC_ORDER_NUMBER INT NOT NULL,
	TSC_NAME VARCHAR(50) NOT NULL,
	TSC_UNIT VARCHAR(50),
	TSC_FORMAT VARCHAR(10),
	TSC_FK_TST_TYPE BIGINT NOT NULL,
	CONSTRAINT PK_TSC_TECHID PRIMARY KEY CLUSTERED (TSC_TECHID),
	CONSTRAINT FK_TSC_FK_TST FOREIGN KEY (TSC_FK_TST_TYPE) REFERENCES choses.T_TS_TIME_SERIE_TYPE(TST_TECHID),
)
CREATE INDEX I_TSC_TECHID ON choses.T_TS_TIME_SERIE_CHANNEL (TSC_TECHID ASC)
CREATE INDEX I_TSC_FK_TST ON choses.T_TS_TIME_SERIE_CHANNEL (TSC_FK_TST_TYPE ASC)


CREATE TABLE choses.T_TS_POINT
(
	POI_TECHID BIGINT IDENTITY(10000,1) NOT NULL,
	TSR_BEG_TIME DATETIME NOT NULL,
	TSR_END_TIME DATETIME,
	TSR_FK_THG_THING BIGINT NOT NULL,
	POI_FK_TST_TYPE BIGINT NOT NULL,
	POI_VALUE DECIMAL(9,2),
	CONSTRAINT PK_POI_TECHID PRIMARY KEY CLUSTERED (POI_TECHID),
	CONSTRAINT FK_POI_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES choses.T_THG_THING(THG_TECHID),
	CONSTRAINT FK_POI_FK_TST_TYPE FOREIGN KEY (POI_FK_TST_TYPE) REFERENCES choses.T_TS_TIME_SERIE_TYPE(TST_TECHID)
)

CREATE INDEX I_POI_TECHID ON choses.T_TS_POINT (POI_TECHID ASC)
CREATE INDEX I_POI_BEG_TIME ON choses.T_TS_POINT (TSR_BEG_TIME ASC)
CREATE INDEX I_POI_END_TIME ON choses.T_TS_POINT (TSR_END_TIME ASC)
CREATE INDEX I_POI_FK_THG_THING ON choses.T_TS_POINT (TSR_FK_THG_THING ASC)
CREATE INDEX I_POI_FK_TST_TYPE ON choses.T_TS_POINT (POI_FK_TST_TYPE ASC)

CREATE TABLE choses.T_TS_GEOLOC
(
	GEO_TECHID BIGINT IDENTITY(10000,1) NOT NULL,

	TSR_BEG_TIME DATETIME NOT NULL,
	TSR_END_TIME DATETIME,
	TSR_FK_THG_THING BIGINT NOT NULL,

	GEO_TYPE CHAR(1) NOT NULL,
	GEO_PROVIDER VARCHAR(16),
	GEO_LONGITUDE DECIMAL(9,2),
	GEO_LATITUDE DECIMAL(9,2),
	GEO_ACCURACY DECIMAL(9,2),

	GEO_FK_PLC_PLACE BIGINT,
	
	CONSTRAINT PK_GEO_TECHID PRIMARY KEY CLUSTERED (GEO_TECHID),
	CONSTRAINT FK_GEO_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES choses.T_THG_THING(THG_TECHID),
)

CREATE INDEX I_GEO_TECHID ON choses.T_TS_GEOLOC (GEO_TECHID ASC)
CREATE INDEX I_GEO_BEG_TIME ON choses.T_TS_GEOLOC (TSR_BEG_TIME ASC)
CREATE INDEX I_GEO_END_TIME ON choses.T_TS_GEOLOC (TSR_END_TIME ASC)
CREATE INDEX I_GEO_FK_THG_THING ON choses.T_TS_GEOLOC (TSR_FK_THG_THING ASC)

CREATE TABLE choses.T_TS_NETWORK
(
	NET_TECHID BIGINT IDENTITY(10000,1) NOT NULL,

	TSR_BEG_TIME DATETIME NOT NULL,
	TSR_END_TIME DATETIME,
	TSR_FK_THG_THING BIGINT NOT NULL,

	NET_TYPE VARCHAR(1) NOT NULL,
	NET_IP VARCHAR(16),
	NET_MAC VARCHAR(8),
	NET_MOBILE_OPERATOR_NAME VARCHAR(32),
	NET_MOBILE_ROAMING TINYINT,
	NET_MOBILE_TYPE VARCHAR(16),
	NET_MOBILE_COUNTRY VARCHAR(16),
	NET_WIFI_BSSID VARCHAR(32),
	NET_WIFI_SSID VARCHAR(32),

	CONSTRAINT PK_NET_TECHID PRIMARY KEY CLUSTERED (NET_TECHID),
	CONSTRAINT FK_NET_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES choses.T_THG_THING(THG_TECHID),
)

CREATE INDEX I_NET_TECHID ON choses.T_TS_NETWORK (NET_TECHID ASC)
CREATE INDEX I_NET_BEG_TIME ON choses.T_TS_NETWORK (TSR_BEG_TIME ASC)
CREATE INDEX I_NET_END_TIME ON choses.T_TS_NETWORK (TSR_END_TIME ASC)
CREATE INDEX I_NET_FK_THG_THING ON choses.T_TS_NETWORK (TSR_FK_THG_THING ASC)



INSERT INTO choses.T_THG_THING_TYPE (TGT_NAME) VALUES ('MobilePhone')

INSERT INTO choses.T_THG_THING_TYPE_PROPERTY (TTP_NAME, TTP_FK_TGT_TYPE)
           SELECT 'IMEI', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME = 'MobilePhone'

INSERT INTO choses.T_THG_THING_TYPE_PROPERTY (TTP_NAME, TTP_FK_TGT_TYPE)
           SELECT 'rp.EMP_REFID', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME = 'MobilePhone'

INSERT INTO choses.T_THG_THING_TYPE (TGT_NAME) VALUES ('Beacon')

INSERT INTO choses.T_THG_THING_TYPE_PROPERTY (TTP_NAME, TTP_FK_TGT_TYPE)
           SELECT 'EddystoneUID', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME = 'Beacon'

INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('LOCATION_v1')

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'Provider', NULL, 'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 10, 'PlaceTechId', NULL, 'long', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 20, 'Longitude', 'dd','double',TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 30, 'Latitude', 'dd','double', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 40, 'Accuracy', 'm','double', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 50, 'Speed', 'm/s','double', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 60,'Bearing', 'deg','double', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LOCATION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('LIGHT_v1')

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'Light', NULL,'int', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'LIGHT_v1'

INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('MOVEMENT_v1')

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'Movement', null,'int', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'MOVEMENT_v1'


INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('NETWORK_CONNECTION_v1')

INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'NETWORK_Type', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 10, 'WIFI_BSSID', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 20, 'WIFI_SSID', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 30, 'WIFI_IP', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 40, 'WIFI_MAC', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 50, 'MOBILE_Ip', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 60, 'MOBILE_Roaming', null,'bool', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 70, 'MOBILE_NetworkType', null,'int', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 80, 'MOBILE_OperatorName', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 90, 'MOBILE_Country', null,'string', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'NETWORK_CONNECTION_v1'

INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('WORKING_v1')
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'value', null,'bool', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'WORKING_v1'


INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('PHONE_BATTERY_LEVEL_v1')
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'value', null,'int', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'PHONE_BATTERY_LEVEL_v1'

INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('PHONE_BATTERY_PLUGGED_v1')
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'value', null,'int', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'PHONE_BATTERY_PLUGGED_v1'

INSERT INTO choses.T_TS_TIME_SERIE_TYPE (TST_REFID) VALUES ('PHONE_SCREEN_ON_OFF_v1')
INSERT INTO choses.T_TS_TIME_SERIE_CHANNEL(TSC_ORDER_NUMBER, TSC_NAME,TSC_UNIT,TSC_FORMAT,TSC_FK_TST_TYPE) 
           SELECT 0, 'value', null,'int', TST_TECHID FROM choses.T_TS_TIME_SERIE_TYPE WHERE TST_REFID = 'PHONE_SCREEN_ON_OFF_v1'

INSERT INTO choses.T_PLC_PLACE_TYPE
           (PLT_NAME, PLT_OFFICE)
	     VALUES (
			'Bureau imad', 
			1)

INSERT INTO choses.T_PLC_PLACE
           (PLC_NAME
		   ,PLC_REFID
           ,PLC_LATITUDE
           ,PLC_LONGITUDE
           ,PLC_SHAPE
           ,PLC_FK_PLT_TYPE)     
			SELECT 
			'CAC Centre Administratif Carouge', 
			'PLC@CAC',
			46.185642,
			6.143487,
			'46.185809,6.144026|46.185568,6.143913|46.185423,6.144412|46.185055,6.144246|46.185174,6.143629|46.185259,6.143661|46.185456,6.142964|46.186019,6.143267|46.185809,6.144026',
			PLT_TECHID FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Chemin de Vers 8, Plan-Les-Ouates', 'PLC@CV8PLO', 46.185642, 6.143487, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Chemin des Clochetons 1, Petit-Lancy', 'PLC@CC1PL', 46.189523, 6.116525, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Boulevard Carl-Vogt 2, Genève', 'PLC@BCV2GE', 46.200980, 6.130343, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Boulevard du Pont-D Arve 28, Genève', 'PLC@BPA28GE', 46.195233, 6.142448, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue de Carouge 46, Genève', 'PLC@RC46GE', 46.194377, 6.143321, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Route de Saint-Julien 176, Plan-Les-Ouates', 'PLC@RSJ176PLO', 46.167420, 6.114838, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue de Lausanne 45-47a, Genèves', 'PLC@RL4547GE', 46.213811, 6.145547, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue Sonnex 3-5, Le Grand-Saconnex', 'PLC@RS35GSA', 46.228306, 6.081866, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue des Vernes 14, Meyrin', 'PLC@RV14MEY', 46.235786, 6.078328, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue du Fort-Barreau 19, Genève', 'PLC@RFB19GE', 46.211449, 6.140107, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue de la Servette 91, Genève', 'PLC@RS91GE', 46.213204, 6.130179, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'


INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Route de Meyrin 18, Genève', 'PLC@RM18GE', 46.215188, 6.126154, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue du Grand-Pré 64-66, Genève', 'PLC@RGP64GE', 46.215974, 6.132200, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Rue des Vollandes 38, Genève', 'PLC@RV38GE', 46.203493, 6.161858, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Chemin des Etournelles 4, Veyrier', 'PLC@CE4VER', 46.168751, 6.182023, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Chemin de la Montagne 136, Chêne-Bougeries', 'PLC@CM136CBR', 46.204402, 6.199974, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Chemin du Vieux-Vésenaz 2, Vésenaz', 'PLC@CVV2VES', 46.236819, 6.195762, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Avenue Dumas 25c, Genève', 'PLC@AD25GE', 46.190135, 6.157277, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Route de Chancy 98, Onex', 'PLC@RC98ONX', 46.185825, 6.104874, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Avenue de Châtelaine 81b, Châtelaine', 'PLC@AC81CHA', 46.210863, 6.112785, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Avenue Louis-Casaï 18, Genève', 'PLC@ALC18GE', 46.219390, 6.115187, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_FK_PLT_TYPE)     
			SELECT  'Avenue du Lignon 78, Le Lignon', 'PLC@AL78LLI', 46.205634, 6.097040, PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'

INSERT INTO choses.T_PLC_PLACE (PLC_NAME,PLC_REFID,PLC_LATITUDE,PLC_LONGITUDE,PLC_SHAPE,PLC_FK_PLT_TYPE)
			SELECT  'La casa de Tibo', 'PLC@TIBO', 46.513747, 6.703985, '46.513714, 6.703631|46.513919, 6.703964|46.513679, 6.704181|46.513524, 6.703787', PLT_TECHID
			FROM choses.T_PLC_PLACE_TYPE WHERE PLT_NAME = 'Bureau imad'
			
INSERT INTO choses.T_SYN_TABLE (STA_TABLE,STA_LAST_UPDATE) VALUES('Place', CURRENT_TIMESTAMP)

INSERT INTO choses.T_SYN_TABLE (STA_TABLE,STA_LAST_UPDATE) VALUES('TimeSerieType', CURRENT_TIMESTAMP)


INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'MOB.TEST1', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='MobilePhone'
INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT '354607086785734', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'IMEI') FROM choses.T_THG_THING WHERE THG_REFID = 'MOB.TEST1'

INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'BC.001001', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='Beacon'

INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT 'afa87cbdb5441ef94e001001', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'EddystoneUID') FROM choses.T_THG_THING WHERE THG_REFID = 'BC.001001'


INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'BC.001002', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='Beacon'

INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT 'afa87cbdb5441ef94e001002', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'EddystoneUID') FROM choses.T_THG_THING WHERE THG_REFID = 'BC.001002'

INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'BC.001003', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='Beacon'

INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT 'afa87cbdb5441ef94e001003', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'EddystoneUID') FROM choses.T_THG_THING WHERE THG_REFID = 'BC.001003'

INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'BC.002001', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='Beacon'

INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT 'afa87cbdb5441ef94e002001', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'EddystoneUID') FROM choses.T_THG_THING WHERE THG_REFID = 'BC.002001'

INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'BC.002002', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='Beacon'

INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT 'afa87cbdb5441ef94e002002', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'EddystoneUID') FROM choses.T_THG_THING WHERE THG_REFID = 'BC.002002'

INSERT INTO choses.T_THG_THING (THG_REFID,THG_FK_TGT_TYPE)
	SELECT	'BC.002003', TGT_TECHID FROM choses.T_THG_THING_TYPE WHERE TGT_NAME='Beacon'

INSERT INTO choses.T_THG_PROPERTY_VALUE (TPV_VALUE, TPV_FK_THG_THING, TPV_FK_TTP_TYPE)
	SELECT 'afa87cbdb5441ef94e002003', THG_TECHID, (SELECT TTP_TECHID FROM choses.T_THG_THING_TYPE_PROPERTY WHERE TTP_NAME = 'EddystoneUID') FROM choses.T_THG_THING WHERE THG_REFID = 'BC.002003'
