sql:
   url: "jdbc:mariadb://localhost:3306/lasrosasiot"
   username: "lasrosasiot"
   password: "lasrosasiot"
influxdb:
   server: "localhost"
   username: "lasrosasiot"
   password: "lasrosasiot"
lora-servers:
-  rak7249:
      mqtt:
         clientid: "Ingester"
         server: "localhost"
         cleanSession: Yes
mqtt:
   clientid: "Ingester"
   server: "localhost"
   cleanSession: Yes