hibernate:
  discriminator:
    ignore_explicit_for_joined:true
influxdb:
   server: localhost
   org: las-rosas.es
   token: FiA6bCJR2nfreCm1XFgnYM5WGv5WNhbXYRvJmxkLP_pMcS-R23vQtaKNz_z19X0ubR_TLC01FfKb8OKKkIYX_w==
   bucket: LasRosasIotUnitTest
rak7249:
  mqtt:
     clientId: lasRosasFlux
     persistFolder: target/mqtt-rak7249
  connect:
     serverURIs:
       - tcp://@localhost:1883
publish:
  mqtt:
     clientId: lasRosasFlux
     persistFolder: target/mqtt-localbroker
  connect:
     serverURIs:
       - tcp://@localhost:1883
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/lasrosasiot
    username: lasrosasiot
    password: lasrosasiot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        physical_naming_strategy: com.lasrosas.iot.core.database.UpperCaseNamingStrategy
logging:
  level:
    org.springframework.orm: INFO
    org.springframework.transaction: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: INFO
    com.lasrosas.iot: DEBUG
    org.eclipse.paho.client: DEBUG
