
/*
   -------------------------------- PROVISIONING ----------------------------------------------
*/

CREATE TABLE T_THG_GATEWAY
(
	GTW_TECHID INT UNSIGNED AUTO_INCREMENT,
	GTW_NATURAL_ID VARCHAR(50),
	GTW_PROTOCOL VARCHAR(50) DEFAULT NULL,
	GTW_URL VARCHAR(50) DEFAULT NULL,
	GTW_LOGIN VARCHAR(50) DEFAULT NULL,
	GTW_PASSWORD VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (GTW_TECHID)
);

CREATE TABLE T_THG_THING_TYPE
(
	TTY_TECHID INT UNSIGNED AUTO_INCREMENT,
	TTY_READABLE VARCHAR(50) DEFAULT NULL,
	TTY_MANUFACTURER VARCHAR(32),
	TTY_MODEL VARCHAR(32),
	TTY_VERSION VARCHAR(16),
	TTY_MAX_HOURS_INVISIBLE REAL DEFAULT NULL,
	TTY_MIN_BATTERY_VOLTAGE REAL DEFAULT NULL,
	TTY_MAX_BATTERY_VOLTAGE REAL DEFAULT NULL,
	BTY_RSSI_1_METER INTEGER,

	PRIMARY KEY (TTY_TECHID)
);

CREATE TABLE T_THG_THING
(
	THG_TECHID INT UNSIGNED AUTO_INCREMENT,
	THG_READABLE VARCHAR(50) DEFAULT NULL,
	THG_DISCRIMINATOR VARCHAR(3) NOT NULL,
	THG_FK_TTY_TYPE INT UNSIGNED NOT NULL,
	THG_FK_GTW_GATEWAY INT UNSIGNED,
	THG_LDTY_VISIBLE datetime DEFAULT NULL,
	THG_MODE VARCHAR(10) DEFAULT 'enabled' NOT NULL,
	BCO_EDDYSTONE_UID VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_UUID VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_MAJOR VARCHAR(50) DEFAULT NULL,
	BCO_IBEACON_MINOR VARCHAR(50) DEFAULT NULL,
	LOR_DEV_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_KEY VARCHAR(50) DEFAULT NULL,
	WIF_BSSID VARCHAR(50) DEFAULT NULL,
	WIF_SSID VARCHAR(50) DEFAULT NULL,
	MOB_IMEI VARCHAR(30) DEFAULT NULL,
	TST_SERIAL VARCHAR(30) DEFAULT NULL,
	WST_STATION_ID VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (THG_TECHID),
	CONSTRAINT FK_THG_FK_TTY_TYPE FOREIGN KEY (THG_FK_TTY_TYPE) REFERENCES T_THG_THING_TYPE(TTY_TECHID),
	CONSTRAINT FK_THG_FK_GTW_GATEWAY FOREIGN KEY (THG_FK_GTW_GATEWAY) REFERENCES T_THG_GATEWAY (GTW_TECHID),
	CONSTRAINT FK_THG_MODE CHECK(THG_MODE IN ('Enabled', 'Disabled', 'Suspended'))
);

/*
   -------------------------------- TIMESERIES ----------------------------------------------
*/

CREATE TABLE T_TSR_TIME_SERIE_TYPE
(
	TST_TECHID INT UNSIGNED AUTO_INCREMENT,
	TST_READABLE VARCHAR(50) DEFAULT NULL,
	TST_SCHEMA VARCHAR(4000) DEFAULT NULL,
	PRIMARY KEY (TST_TECHID)
);

CREATE TABLE T_TSR_TIME_SERIE
(
	TSR_TECHID INT UNSIGNED AUTO_INCREMENT,
	TSR_SENSOR VARCHAR(16) DEFAULT NULL,
	TSR_FK_THG_THING INT UNSIGNED NOT NULL,
	TSR_FK_TST_TYPE INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (TSR_TECHID),
	CONSTRAINT FK_TSR_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_TSR_FK_TST_TYPE FOREIGN KEY (TSR_FK_TST_TYPE) REFERENCES T_TSR_TIME_SERIE_TYPE(TST_TECHID)
);

CREATE TABLE T_TSR_POINT
(
	POI_TECHID INT UNSIGNED AUTO_INCREMENT,
	POI_FK_TSR_TIME_SERIE INT UNSIGNED,
	POI_VALUE VARCHAR(2048) DEFAULT NULL,
	POI_TIME  TIMESTAMP(6),
	PRIMARY KEY (POI_TECHID)
);
