
/*
   -------------------------------- DIGITAL TWIN --------------------------------------------
*/

CREATE TABLE T_DTW_SPACE
(
	SPA_TECHID INT UNSIGNED AUTO_INCREMENT,
	SPA_NAME VARCHAR(50) DEFAULT NULL,

	PRIMARY KEY (SPA_TECHID)
);

CREATE TABLE T_DTW_DIGITAL_TWIN_TYPE
(
	TWT_TECHID INT UNSIGNED AUTO_INCREMENT,
	TWT_NAME VARCHAR(50) DEFAULT NULL,
	TWT_DISCRIMINATOR VARCHAR(3) NOT NULL,
	TWT_MAY_HAVE_CHILDREN BIT DEFAULT 0,
	TWT_FK_SPA_SPACE INT UNSIGNED NOT NULL,
	TWT_PUBLISH_ONTHOLOGY BIT DEFAULT 0,
	DTT_FK_DTT_SUPER_TYPE INT UNSIGNED DEFAULT NULL
	DTT_CONCRETE BIT DEFAULT 1,

	PRIMARY KEY (TWT_TECHID),
	CONSTRAINT FK_DTT_FK_DTT_SUPER_TYPE FOREIGN KEY (DTT_FK_DTT_SUPER_TYPE) REFERENCES T_DTW_DIGITAL_TWIN_TYPE (TWT_TECHID),
	CONSTRAINT FK_TWT_FK_SPA_SPACE FOREIGN KEY (TWT_FK_SPA_SPACE) REFERENCES T_DTW_SPACE (SPA_TECHID)
);

CREATE TABLE T_DTW_DIGITAL_TWIN
(
	TWI_TECHID INT UNSIGNED AUTO_INCREMENT,
	TWI_DISCRIMINATOR VARCHAR(3) NOT NULL,
	TWI_NAME VARCHAR(50),
	TWI_FK_TWT_TYPE INT UNSIGNED NOT NULL,
	TWI_FK_TWI_PART_OF INT UNSIGNED DEFAULT NULL,
	TWI_PROPERTIES VARCHAR(4000) DEFAULT NULL,

	PRIMARY KEY (TWI_TECHID),
	CONSTRAINT FK_TWI_FK_TWI_PART_OF FOREIGN KEY (TWI_FK_TWI_PART_OF) REFERENCES T_DTW_DIGITAL_TWIN(TWI_TECHID),
	CONSTRAINT FK_TWI_FK_TWT_TYPE FOREIGN KEY (TWI_FK_TWT_TYPE) REFERENCES T_DTW_DIGITAL_TWIN_TYPE(TWT_TECHID)
);
CREATE TABLE `T_DTW_DIGITAL_TWIN` (
  `TWI_TECHID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TWI_DISCRIMINATOR` varchar(3) NOT NULL,
  `TWI_NAME` varchar(50) DEFAULT NULL,
  `TWI_FK_TWT_TYPE` int(10) unsigned NOT NULL,
  `TWI_FK_TWI_PART_OF` int(10) unsigned DEFAULT NULL,
  `TWI_PROPERTIES` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`TWI_TECHID`),
  KEY `FK_TWI_FK_TWT_TYPE` (`TWI_FK_TWT_TYPE`),
  KEY `FK_TWI_FK_TWI_PARTOF` (`TWI_FK_TWI_PART_OF`),
  CONSTRAINT `FK_TWI_FK_TWI_PARTOF` FOREIGN KEY (`TWI_FK_TWI_PART_OF`) REFERENCES `T_DTW_DIGITAL_TWIN` (`TWI_TECHID`),
  CONSTRAINT `FK_TWI_FK_TWT_TYPE` FOREIGN KEY (`TWI_FK_TWT_TYPE`) REFERENCES `T_DTW_DIGITAL_TWIN_TYPE` (`TWT_TECHID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `T_DTW_WATER_TANK` (
  `TWI_TECHID` int(10) unsigned NOT NULL,
  `WAT_LENGTH` double NOT NULL,
  `WAT_RADIUS` double NOT NULL,
  `WAT_SENSOR_ALT` double NOT NULL,
  `WAT_VOLUME_MAX` double DEFAULT NULL,
  `WAT_LEVEL` double DEFAULT NULL,
  `WAT_VOLUME` double DEFAULT NULL,
  `WAT_PERCENTAGE` int(3) DEFAULT NULL,
  `WAT_WATER_FLOW` double  NULL,
  `WAT_MAX_WATER_FLOW` double  NULL,
  PRIMARY KEY (`TWI_TECHID`),
  CONSTRAINT `FK_WAT_TWI_TECHID` FOREIGN KEY (`TWI_TECHID`) REFERENCES `T_DTW_DIGITAL_TWIN` (`TWI_TECHID`)
);

CREATE TABLE `T_DTW_DYNAMIC_TWIN` (
  `TWI_TECHID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`TWI_TECHID`),
  CONSTRAINT `FK_DTW_TWI_TECHID` FOREIGN KEY (`TWI_TECHID`) REFERENCES `T_DTW_DIGITAL_TWIN` (`TWI_TECHID`)
);
/*
   -------------------------------- PROVISIONING ----------------------------------------------
*/

CREATE TABLE T_THG_GATEWAY
(
	GTW_TECHID INT UNSIGNED AUTO_INCREMENT,
	GTW_NATURAL_ID VARCHAR(50),
	GTW_PROTOCOL VARCHAR(50) DEFAULT NULL,
	GTW_URL VARCHAR(50) DEFAULT NULL,
	GTW_LOGIN VARCHAR(50) DEFAULT NULL,
	GTW_PASSWORD VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (GTW_TECHID)
);

CREATE TABLE T_THG_THING_TYPE
(
	TTY_TECHID INT UNSIGNED AUTO_INCREMENT,
	TTY_READABLE VARCHAR(50) DEFAULT NULL,
	TTY_MANUFACTURER VARCHAR(32),
	TTY_MODEL VARCHAR(32),
	TTY_MIN_PERCENTAGE
	TTY_VERSION VARCHAR(16),
	TTY_MAX_HOURS_INVISIBLE REAL DEFAULT NULL,
	TTY_BATTERY_MIN_PERCENTAGE REAL DEFAULT 25,
	BTY_RSSI_1_METER INTEGER,

	PRIMARY KEY (TTY_TECHID)
);

CREATE TABLE T_THG_THING
(
	THG_TECHID INT UNSIGNED AUTO_INCREMENT,
	THG_READABLE VARCHAR(50) DEFAULT NULL,
	THG_DISCRIMINATOR VARCHAR(3) NOT NULL,
	THG_FK_TTY_TYPE INT UNSIGNED NOT NULL,
	THG_FK_GTW_GATEWAY INT UNSIGNED,
	THG_FK_TWI_TWIN INT UNSIGNED NOT NULL,
	THG_LDTY_VISIBLE datetime DEFAULT NULL,
	THG_MODE VARCHAR(10) DEFAULT 'enabled' NOT NULL,
	LOR_DEV_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_EUI VARCHAR(50) DEFAULT NULL,
	LOR_APP_KEY VARCHAR(50) DEFAULT NULL,
	WST_STATION_ID VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (THG_TECHID),
	CONSTRAINT FK_THG_FK_TTY_TYPE FOREIGN KEY (THG_FK_TTY_TYPE) REFERENCES T_THG_THING_TYPE(TTY_TECHID),
	CONSTRAINT FK_THG_FK_TWI_TWIN FOREIGN KEY (THG_FK_TWI_TWIN) REFERENCES T_DTW_DIGITAL_TWIN(TWI_TECHID),
	CONSTRAINT FK_THG_FK_GTW_GATEWAY FOREIGN KEY (THG_FK_GTW_GATEWAY) REFERENCES T_THG_GATEWAY (GTW_TECHID),
	CONSTRAINT FK_THG_MODE CHECK(THG_MODE IN ('Enabled', 'Disabled', 'Removed'))
);

CREATE TABLE T_THG_THING_PROXY
(
	THP_TECHID INT UNSIGNED AUTO_INCREMENT,
	THP_BATTERY_STATE INT UNSIGNED DEFAULT 0,
	THP_CONNECTION_STATE INT UNSIGNED DEFAULT 0,
	THP_BATTERY_LEVEL INT UNSIGNED DEFAULT NULL,
	THP_LAST_SEEN TIMESTAMP(6) NULL DEFAULT NULL,
	THP_CONFIG VARCHAR(4000) DEFAULT NULL,
	THP_VALUES VARCHAR(4000) DEFAULT NULL,
	THP_FK_THG_THING INT UNSIGNED,

	PRIMARY KEY (THP_TECHID),
	CONSTRAINT FK_THP_FK_THG_THING FOREIGN KEY (THP_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID)
);


/*
   -------------------------------- TIMESERIES ----------------------------------------------
*/

CREATE TABLE T_TSR_TIME_SERIE_TYPE
(
	TST_TECHID INT UNSIGNED AUTO_INCREMENT,
	TST_SCHEMA VARCHAR(4000) DEFAULT NULL,
	TST_DIFFUSED BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (TST_TECHID)
);

CREATE TABLE T_TSR_TIME_SERIE
(
	TSR_TECHID INT UNSIGNED AUTO_INCREMENT,
	TSR_SENSOR VARCHAR(16) DEFAULT NULL,
	TSR_INFLUXDB_MEASUREMENT VARCHAR(100) DEFAULT NULL,
	TSR_FK_THG_THING INT UNSIGNED DEFAULT NULL,
	TSR_FK_TST_TYPE INT UNSIGNED DEFAULT NULL,
	TSR_FK_TWI_TWIN INT UNSIGNED DEFAULT NULL,
	TSR_FK_CURRENT_VALUE INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (TSR_TECHID),
	CONSTRAINT FK_TSR_FK_THG_THING FOREIGN KEY (TSR_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_TSR_FK_CURRENT_VALUE FOREIGN KEY (TSR_FK_CURRENT_VALUE) REFERENCES T_TSR_POINT(POI_TECHID),
	CONSTRAINT FK_TSR_FK_TST_TYPE FOREIGN KEY (TSR_FK_TST_TYPE) REFERENCES T_TSR_TIME_SERIE_TYPE(TST_TECHID)
);

CREATE TABLE T_TSR_POINT
(
	POI_TECHID INT UNSIGNED AUTO_INCREMENT,
	POI_FK_TSR_TIME_SERIE INT UNSIGNED,
	POI_VALUE VARCHAR(2048) DEFAULT NULL,
	POI_TIME  TIMESTAMP(6),
	PRIMARY KEY (POI_TECHID)
);

/*--------------- ALARM --------------*/
CREATE TABLE T_ALR_ALARM_TYPE
(
	ALT_TECHID INT UNSIGNED AUTO_INCREMENT,
	ALT_NAME VARCHAR(50) DEFAULT NULL,

	PRIMARY KEY (ALT_TECHID)
);

CREATE TABLE T_ALR_ALARM
(
	ALR_TECHID INT UNSIGNED AUTO_INCREMENT,
	ALR_DISCRIMINATOR VARCHAR(3) NOT NULL,
	ALR_NAME VARCHAR(50),
	ALR_STATE VARCHAR(10),
	ALR_OPENED_TIME datetime DEFAULT NULL,
	ALR_CLOSED_TIME datetime DEFAULT NULL,
	ALR_FK_ALT_TYPE INT UNSIGNED NOT NULL,
	THA_FK_THG_THING INT UNSIGNED DEFAULT NULL,
	TWA_FK_TWI_TWIN INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (ALR_TECHID),
	CONSTRAINT FK_ALR_FK_ALT_TYPE FOREIGN KEY (ALR_FK_ALT_TYPE) REFERENCES T_ALR_ALARM_TYPE(ALT_TECHID),
	CONSTRAINT FK_THA_FK_THG_THING FOREIGN KEY (THA_FK_THG_THING) REFERENCES T_THG_THING(THG_TECHID),
	CONSTRAINT FK_TWA_FK_TWI_TWIN FOREIGN KEY (TWA_FK_TWI_TWIN) REFERENCES T_DTW_DIGITAL_TWIN(TWI_TECHID)

);

